import { NextRequest, NextResponse } from 'next/server'
import { requireScope } from '@/v2/application/authenticate-api-client'
import { readStoryPlanService } from '@/v2/application/story-plans'
import { createStoryPlanRepository } from '@/v2/infrastructure/repository-factory'
import { authenticateExternalRequest } from '@/v2/public-api/authentication'
import { presentStoryPlan } from '@/v2/public-api/story-plan-contract'
import { publicApiHeaders, resolveRequestId, respondPublicError } from '@/v2/public-api/errors'
import { presentSuccess } from '@/v2/public-api/presenters'
export const dynamic = 'force-dynamic'
export async function GET(request: NextRequest, context: { params: Promise<{ projectId: string; storyPlanId: string }> }) { const requestId = resolveRequestId(request); try { const actor = await authenticateExternalRequest(request); requireScope(actor, 'projects:read'); const { projectId, storyPlanId } = await context.params; const value = await readStoryPlanService({ repository: createStoryPlanRepository() })({ workspaceId: actor.workspaceId, projectId, storyPlanId }); return NextResponse.json(presentSuccess({ storyPlan: presentStoryPlan(value) }), { headers: publicApiHeaders(requestId) }) } catch (error) { return respondPublicError(error, requestId) } }
