import { randomUUID } from 'node:crypto'
import { NextRequest, NextResponse } from 'next/server'
import { requireScope } from '@/v2/application/authenticate-api-client'
import { createStoryPlanService } from '@/v2/application/story-plans'
import { DomainError } from '@/v2/domain/errors'
import { createStoryPlanRepository } from '@/v2/infrastructure/repository-factory'
import { authenticateExternalRequest } from '@/v2/public-api/authentication'
import { parseCreateStoryPlanBody, presentStoryPlan } from '@/v2/public-api/story-plan-contract'
import { publicApiHeaders, resolveRequestId, respondPublicError } from '@/v2/public-api/errors'
import { presentSuccess } from '@/v2/public-api/presenters'
export const dynamic = 'force-dynamic'
export async function POST(request: NextRequest, context: { params: Promise<{ projectId: string }> }) { const requestId = resolveRequestId(request); try { const actor = await authenticateExternalRequest(request); requireScope(actor, 'projects:write'); const { projectId } = await context.params; let raw: unknown; try { raw = await request.json() } catch { throw new DomainError('INVALID_ARGUMENT', 'Request body must be valid JSON') }; const body = parseCreateStoryPlanBody(raw); const result = await createStoryPlanService({ repository: createStoryPlanRepository(), createId: () => `story-plan-${randomUUID()}` })({ workspaceId: actor.workspaceId, projectId, ...body, actor, idempotencyKey: request.headers.get('idempotency-key')?.trim() ?? '' }); return NextResponse.json(presentSuccess({ storyPlan: presentStoryPlan(result.value), replayed: result.replayed }), { status: result.replayed ? 200 : 201, headers: publicApiHeaders(requestId) }) } catch (error) { return respondPublicError(error, requestId) } }
