import test from 'node:test';import assert from 'node:assert/strict';import {applySoundBudget,chooseAudioSyncMode,compileAudioDirectionPlan,critiqueAudiovisual,localizationAudioGate,mixAndMaster,searchSoundLibrary} from '../../src/v2/domain/audio-direction.ts';
const event=(id,kind,start,group=id)=>({id,kind,rangeMs:[start,start+500],sourceId:id,gainDb:-6,group,snap:'beat'});
test('T-FR-200 narrative/music/hybrid selection persists reason and speech wins unsafe beat conflicts',()=>{assert.equal(chooseAudioSyncMode({speechImportance:.9,beatConfidence:.9,musicIsPrimary:true}).mode,'hybrid');assert.equal(chooseAudioSyncMode({requested:'narrative-led',speechImportance:.2,beatConfidence:1,musicIsPrimary:true}).priority,'speech');});
test('T-FR-201 AudioDirectionPlan compiles deterministically with protected events and range overrides',()=>{const plan={version:1,mode:'hybrid',musicSections:[{id:'s',rangeMs:[0,10000],energy:.5}],beatGridMs:[0,1000],events:[{...event('music','music',0),protected:true},event('fx','sfx',1000)],transitions:[{atMs:1000,kind:'crossfade',durationMs:20}],ducking:{speechTrack:'voice',musicTrack:'music',reductionDb:-8,attackMs:80,releaseMs:300},mix:{speechLufs:-16,musicLufs:-24,sfxLufs:-22,roomToneLufs:-40,targetLufs:-14,truePeakDb:-1},overrides:[{rangeMs:[0,2000],values:{gainDb:-20}}]};const compiled=compileAudioDirectionPlan(plan);assert.equal(compiled.tracks.events[0].gainDb,-6);assert.equal(compiled.tracks.events[1].gainDb,-20);});
test('T-FR-202 sound library analyzes and searches function/energy/theme only after rights filters',()=>{const asset={id:'m',kind:'music',bpm:120,key:'C',mood:['hope'],durationMs:10000,rights:{territories:['BR'],channels:['instagram'],expiresAt:'2030-01-01'},metadata:{version:1,waveform:[0,.5],loudnessLufs:-18,truePeakDb:-1,beatGridMs:[0,500],sections:[{rangeMs:[0,10000],energy:.6}]},function:'background',energy:.6,theme:['growth']};assert.equal(searchSoundLibrary([asset],{function:'background',energy:.5,theme:['growth'],territory:'BR',channel:'instagram',now:'2026-01-01'})[0].asset.id,'m');assert.equal(searchSoundLibrary([asset],{function:'background',energy:.5,theme:[],territory:'US',channel:'instagram',now:'2026-01-01'}).length,0);});
test('T-FR-203 sound budget removes repeated/dense SFX before render and reports tone',()=>{const result=applySoundBudget([event('a','sfx',0,'whoosh'),event('b','sfx',100,'whoosh'),event('c','stinger',200)],{windowMs:1000,maxDensity:2,cooldownMs:500,maxIntensity:3,intensityByKind:{sfx:1,stinger:2}});assert.equal(result.accepted.length,2);assert.deepEqual(result.removed.map(x=>x.reason),['repetition-cooldown']);assert.equal(result.tone,'adequate');});
test('T-FR-204 mix stages voice/music/SFX/room tone, ducks speech and preserves tails without clicks',()=>{const result=mixAndMaster({events:[event('music','music',0),event('hit','sfx',1000)],speechRanges:[[0,700]],targetLufs:-14,truePeakDb:-1,destination:'instagram',sampleRate:48000});assert.equal(result.automation[0].gainDb,-14);assert.equal(result.automation[1].preserveTailMs,250);assert.equal(result.report.clippedSamples,0);});
test('T-FR-205 audiovisual critic localizes hard masking/clipping and calibrated beat/tail warnings',()=>{const result=critiqueAudiovisual({tracks:[{id:'music',kind:'music',rangeMs:[0,1000],speechMasking:.4,driftMs:0,clipping:0,pumping:.1,tailCut:.2,beatMismatchMs:150}]});assert.equal(result.passed,false);assert.equal(result.issues.find(x=>x.metric==='speechMasking').patch,'increase-ducking');assert.ok(result.warnings.some(x=>x.metric==='beatMismatchMs'));});
test('T-F5-GATE produces PT/EN/ES × 9:16/16:9 with locale timing, consent modes and valid mixes',()=>{const locales=[{locale:'pt-BR',audioId:'pt',alignmentWords:10,timelineId:'tpt',subtitleId:'spt',cta:'Comprar',mode:'uploaded',localizedAssets:1},{locale:'en-US',audioId:'en',alignmentWords:11,timelineId:'ten',subtitleId:'sen',cta:'Buy',mode:'lip-sync',localizedAssets:2},{locale:'es-ES',audioId:'es',alignmentWords:12,timelineId:'tes',subtitleId:'ses',cta:'Comprar',mode:'subtitles-only',localizedAssets:2}];const gate=localizationAudioGate({locales,formats:['9:16','16:9'],narrativeMixPassed:true,hybridMixPassed:true,musicLedSpeechPreserved:true});assert.equal(gate.passed,true);assert.equal(gate.outputs,6);});
