import test from 'node:test';
import assert from 'node:assert/strict';
import { addCaptureTrack, alignSeparateAudio, chooseSyncStrategy, coverageDiagnostic, detectClockPieces, fitDrift, sessionToSource, sourceToSession, synthesizeEditorialStory } from '../../src/v2/domain/capture-synchronization.ts';

const track = (id, role, coverage = [[0, 10000]], timebase = 48000, events = []) => ({ id, role, device: id, assetId: `${id}.mp4`, timebase, coverage, events, includeInFinalMix: role === 'audio-master' });
test('T-FR-135 builds explicit multi-range 2min story preserving claims and context', () => { const story = synthesizeEditorialStory([{ sourceId: 'live', rangeMs: [0, 60000], text: 'A', claim: 'cresceu', qualifier: 'no trimestre', attribution: 'relatório' }, { sourceId: 'live', rangeMs: [3000000, 3060000], text: 'B' }], 'conteúdo'); assert.equal(story.durationMs, 120000); assert.equal(story.claims[0].qualifier, 'no trimestre'); assert.equal(story.bridges[0].supported, true); });
test('T-FR-140 groups camera, screen, separate audio and reference while retaining clocks/coverage', () => { let session = { id: 'session', clockRate: 1000, tracks: [track('camera', 'camera')] }; session = addCaptureTrack(session, track('screen', 'screen', [[2000, 9000]], 1000)); assert.equal(session.tracks[1].coverage[0][0], 2000); assert.equal(session.tracks[0].timebase, 48000); });
test('T-FR-141 clock mapping is monotonic and round-trips numeric boundaries', () => { const piece = { sourceRange: [0, 10000], sessionRange: [100, 10100], rate: 1, offset: 100, precisionMs: 2, confidence: .99 }; for (const value of [0, 1, 5000, 9999, 10000]) assert.ok(Math.abs(sessionToSource(piece, sourceToSession(piece, value)) - value) < 1e-9); assert.throws(() => sourceToSession(piece, 10001)); });
test('T-FR-142 cascades evidence and refuses false precision with no common signal', () => { assert.equal(chooseSyncStrategy([{ method: 'audio-fingerprint', score: .9, anchors: [] }, { method: 'marker', score: .9, anchors: [] }]).selected.method, 'marker'); assert.equal(chooseSyncStrategy([{ method: 'visual-event', score: .3, anchors: [] }]).status, 'insufficient-evidence'); });
test('T-FR-143 coverage blocks short/gapped source selections and reports internal gaps', () => { const diagnostic = coverageDiagnostic(track('split', 'camera', [[0, 1000], [2000, 4000]]), [900, 2100]); assert.equal(diagnostic.available, false); assert.deepEqual(diagnostic.gaps, [[1000, 2000]]); });
test('T-FR-144 estimates offset/rate/ppm and detects nonlinear unsafe speech drift', () => { const linear = fitDrift([{ sourceMs: 0, sessionMs: 10 }, { sourceMs: 100000, sessionMs: 100020 }]); assert.ok(Math.abs(linear.ppm - 100) < .001); const nonlinear = fitDrift([{ sourceMs: 0, sessionMs: 0 }, { sourceMs: 50000, sessionMs: 50100 }, { sourceMs: 100000, sessionMs: 100000 }]); assert.equal(nonlinear.nonlinear, true); });
test('T-FR-145 detects restart/gap and maps only valid continuous pieces', () => { const pieces = detectClockPieces([{ pts: 0 }, { pts: 1000 }, { pts: 500 }, { pts: 5000 }]); assert.deepEqual(pieces.map(item => item.reason), ['rewind-or-restart', 'gap', 'continuous']); });
test('T-FR-146 aligns unequal camera/screen duration to master and discards scratch audio', () => { const session = { id: 's', clockRate: 1000, tracks: [track('master', 'audio-master'), track('camera', 'camera', [[1000, 8000]], 44100), track('screen', 'screen', [[0, 5000]], 1000, [{ type: 'silence', pts: 0 }]), track('scratch', 'scratch-audio')] }; const signals = Object.fromEntries(session.tracks.slice(1).map(item => [item.id, [{ method: 'manual-anchor', score: .9, anchors: [{ sourceMs: 0, sessionMs: 1000 }] }]])); const result = alignSeparateAudio(session, 'master', signals); assert.ok(result.every(item => item.finalAudioId === 'master')); assert.ok(result.find(item => item.trackId === 'camera').warnings.includes('sample-rate-mismatch')); assert.equal(result.find(item => item.trackId === 'scratch').discardScratch, true); });
