import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { annotationToMask, applyProviderCallback, calculateNovelty, chooseFallback, createProviderJob, critiqueTransformation, MODE_CONTRACTS, planAdvancedCleanup, resumeProviderJob, routeTransformation, TRANSFORMATION_GOLDENS, TRANSFORMATION_MODES } from '../../src/v2/domain/generative-transformation.ts';

test('T-FR-110 creates minimal immutable briefs for simple and medieval intents', () => { assert.equal(TRANSFORMATION_GOLDENS.medieval.preserve.includes('identity'), true); assert.deepEqual(TRANSFORMATION_GOLDENS.medieval.sourceRefs, ['scene-2']); });
test('T-FR-111 declares six capability contracts and valid fallbacks without provider branches', () => { assert.equal(TRANSFORMATION_MODES.length, 6); assert.ok(TRANSFORMATION_MODES.every(mode => MODE_CONTRACTS[mode].fallback)); });
test('T-FR-112 routes by capability, health, region, limits, cost and quality while preserving brief', () => { const brief = TRANSFORMATION_GOLDENS.simple; const before = JSON.stringify(brief); const routed = routeTransformation(brief, [{ provider: 'a', capability: 'relight', healthy: true, circuitOpen: false, limits: { maxDurationMs: 10000 }, regions: ['br'], pricePerSecond: .1, quality: .9, credentialsRef: 'vault:a' }, { provider: 'b', capability: 'relight', healthy: false, circuitOpen: true, limits: { maxDurationMs: 10000 }, regions: ['br'], pricePerSecond: .01, quality: 1, credentialsRef: 'vault:b' }], { region: 'br', maxCost: 2, minQuality: .8 }); assert.equal(routed.selected.provider, 'a'); assert.equal(JSON.stringify(brief), before); });
test('T-FR-113 durable jobs resume and reject forged/replayed callbacks', () => { let job = createProviderJob(TRANSFORMATION_GOLDENS.simple, 'webhook'); job = resumeProviderJob(job); const secret = 'secret', nonce = 'n1', signature = createHash('sha256').update(`${job.correlationId}:${nonce}:${secret}`).digest('hex'), consumed = new Set(); const completed = applyProviderCallback(job, { correlationId: job.correlationId, artifact: 'result.mp4', signature, nonce }, secret, consumed); assert.equal(completed.job.state, 'completed'); assert.equal(applyProviderCallback(job, { correlationId: job.correlationId, artifact: 'result.mp4', signature, nonce }, secret, consumed).duplicate, true); assert.throws(() => applyProviderCallback(job, { correlationId: job.correlationId, signature: '00', nonce: 'n2' }, secret, consumed)); });
test('T-FR-114 novelty budget yields sober, balanced and rejects exaggerated repetition', () => { const result = calculateNovelty({ transformations: [{ group: 'zoom', novelty: .2, durationMs: 1000, atMs: 0 }, { group: 'zoom', novelty: .8, durationMs: 2000, atMs: 500 }, { group: 'relight', novelty: .4, durationMs: 1000, atMs: 3000 }], windowMs: 1000, limit: 1 }); assert.equal(result.treatment, 'balanced'); assert.equal(result.rejected.length, 1); });
test('T-FR-115 fallback preserves best artifact and cost while respecting intent', () => { const result = chooseFallback(TRANSFORMATION_GOLDENS.medieval, [{ mode: 'v2v', valid: false, intentScore: .9, artifact: 'bad.mp4', cost: 4 }, { mode: 'composite', valid: true, intentScore: .8, artifact: 'good.mp4', cost: 2 }]); assert.equal(result.applied, 'composite'); assert.equal(result.preservedArtifact, 'good.mp4'); assert.equal(result.incurredCost, 6); });
test('T-FR-116 critic rejects subtle protected identity change despite visual quality', () => { const result = critiqueTransformation(TRANSFORMATION_GOLDENS.medieval, { intent: .98, temporal: .96, artifacts: .02, risk: .05, changed: ['identity'], regionScores: [{ rangeMs: [2000, 3000], score: .6 }] }); assert.equal(result.passed, false); assert.equal(result.issue.code, 'protected-content-changed'); });
test('T-FR-123 advanced cleanup requires confident reviewed mask and immutable derivative', () => { const mask = annotationToMask({ pixels: { x: 100, y: 50, width: 200, height: 100 }, canvas: { width: 1000, height: 500 }, rangeMs: [0, 2000], confidence: .9, format: '9:16' }); const plan = planAdvancedCleanup({ mask, sourceId: 'source', operation: 'inpaint', qualityThreshold: .8, estimated: { quality: .9, cost: 4 }, alternatives: [{ method: 'crop', quality: .85, cost: 1 }] }); assert.equal(plan.immutableSource, true); assert.equal(plan.chosen.cost, 1); });
test('T-FR-218 converts review annotation into normalized tracked mask and flags uncertainty', () => { const mask = annotationToMask({ pixels: { x: 100, y: 50, width: 200, height: 100 }, canvas: { width: 1000, height: 500 }, rangeMs: [0, 2000], confidence: .5, format: '16:9' }); assert.deepEqual(mask.normalized, { x: .1, y: .1, width: .2, height: .2 }); assert.equal(planAdvancedCleanup({ mask, sourceId: 's', operation: 'inpaint', qualityThreshold: .8, estimated: { quality: 1, cost: 2 }, alternatives: [] }).status, 'needs-mask-review'); });
test('T-F3-GATE changes providers without changing domain and falls back after rejection', () => { const routed = routeTransformation(TRANSFORMATION_GOLDENS.medieval, [{ provider: 'fake', capability: 'background-replacement', healthy: true, circuitOpen: false, limits: { maxDurationMs: 10000 }, regions: ['br'], pricePerSecond: .1, quality: .9, credentialsRef: 'vault' }], { region: 'br', maxCost: 10, minQuality: .8 }); assert.equal(routed.selected.provider, 'fake'); assert.equal(chooseFallback(TRANSFORMATION_GOLDENS.medieval, [{ mode: 'v2v', valid: false, intentScore: .4, cost: 1 }, { mode: 'unchanged', valid: true, intentScore: .8, cost: 0 }]).applied, 'unchanged'); });
