import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import test from 'node:test'

import {
  SYNTHETIC_MASTER_ARTIFACT_ROLES,
  assertSyntheticMasterIntegrity,
  calculateSyntheticMasterHash,
  createSyntheticMasterAsset,
  findSyntheticMasterArtifact,
} from '../../src/v2/domain/synthetic-master-asset.ts'

const digest = (character) => character.repeat(64)

const artifacts = [
  { role: 'provider-original', artifactId: 'artifact-original', sha256: digest('a'), byteSize: 2_048, mediaType: 'video', container: 'mp4' },
  { role: 'normalized-video', artifactId: 'artifact-normalized', sha256: digest('b'), byteSize: 3_072, mediaType: 'video', container: 'mp4' },
  { role: 'final-audio', artifactId: 'artifact-audio', sha256: digest('c'), byteSize: 1_024, mediaType: 'audio', container: 'wav' },
  { role: 'alignment', artifactId: 'artifact-alignment', sha256: digest('d'), byteSize: 512, mediaType: 'data', container: 'json' },
]

const base = {
  id: 'synthetic-master-1',
  workspaceId: 'workspace-1',
  projectId: 'project-1',
  projectVersionId: 'project-version-1',
  profileId: 'ana',
  profileSnapshotId: 'ana-v2',
  profileVersion: 2,
  consentSnapshotHash: digest('e'),
  authorizationHash: digest('f'),
  rightsSnapshotId: 'rights-1',
  artifacts,
  scriptText: 'Uma frase completa. Outra reflexão.',
  alignmentHash: digest('1'),
  locale: 'pt-BR',
  durationMs: 4_000,
  audioDurationMs: 4_000,
  videoDurationMs: 4_010,
  provenance: {
    adapterId: 'heygen-v3',
    adapterVersion: '3.0.0',
    capability: 'audio-avatar',
    modelRef: 'avatar-model-1',
    adapterConfigHash: digest('2'),
    providerJobId: 'provider-job-1',
    providerJobRef: 'heygen_job_1',
  },
  cost: { currency: 'USD', minorUnits: 150, latencyMs: 8_400 },
  critic: { reportId: 'critic-report-1', reportHash: digest('3'), decision: 'approved' },
  lineage: ['generation-1', 'generation-2'],
  createdAt: '2026-08-30T12:00:00.000Z',
}

test('T-FR-104 a synthetic master seals every generated byte with its provenance and content address', () => {
  const master = createSyntheticMasterAsset(base)

  // Every ingested role is present, canonically ordered and content-addressed.
  assert.deepEqual(master.artifacts.map(({ role }) => role), [...SYNTHETIC_MASTER_ARTIFACT_ROLES])
  assert.equal(findSyntheticMasterArtifact(master, 'final-audio').sha256, digest('c'))
  assert.equal(master.scriptHash, createHash('sha256').update(base.scriptText, 'utf8').digest('hex'))
  assert.match(master.masterHash, /^[a-f0-9]{64}$/)
  assert.equal(assertSyntheticMasterIntegrity(master), master)

  // Composition is derived: the master carries no caption, LUT, B-roll or
  // output-format decision that a later edit could invalidate.
  for (const forbidden of ['captions', 'lut', 'broll', 'overlays', 'composition', 'outputFormat']) {
    assert.equal(Object.hasOwn(master, forbidden), false, `master must not own ${forbidden}`)
  }

  // The same performance always produces the same address; a different one never does.
  assert.equal(createSyntheticMasterAsset(base).masterHash, master.masterHash)
  assert.notEqual(
    createSyntheticMasterAsset({ ...base, id: 'synthetic-master-2' }).masterHash,
    master.masterHash,
  )
  assert.equal(
    createSyntheticMasterAsset({ ...base, artifacts: [...artifacts].reverse() }).masterHash,
    master.masterHash,
    'artifact insertion order must not change the master address',
  )
  assert.notEqual(
    createSyntheticMasterAsset({
      ...base,
      artifacts: artifacts.map((entry) => entry.role === 'final-audio' ? { ...entry, sha256: digest('9') } : entry),
    }).masterHash,
    master.masterHash,
    'different audio bytes must produce a different master',
  )
})

test('T-FR-104 a master refuses to exist without complete, coherent and approved evidence', () => {
  const withoutAudio = artifacts.filter(({ role }) => role !== 'final-audio')
  assert.throws(() => createSyntheticMasterAsset({ ...base, artifacts: withoutAudio }), /missing its final-audio artifact/)
  assert.throws(
    () => createSyntheticMasterAsset({ ...base, artifacts: [...artifacts, artifacts[2]] }),
    /final-audio is duplicated/,
  )
  assert.throws(
    () => createSyntheticMasterAsset({
      ...base,
      artifacts: artifacts.map((entry) => entry.role === 'final-audio' ? { ...entry, mediaType: 'video' } : entry),
    }),
    /cannot carry media type video/,
  )

  // Audio governs the timeline, and a video that drifts past a frame is not
  // the same performance.
  assert.throws(() => createSyntheticMasterAsset({ ...base, durationMs: 3_900 }), /must equal the audio duration/)
  assert.throws(() => createSyntheticMasterAsset({ ...base, videoDurationMs: 4_600 }), /disagree beyond one frame/)

  // Only an approved critic report can seal a master.
  assert.throws(
    () => createSyntheticMasterAsset({ ...base, critic: { ...base.critic, decision: 'rejected' } }),
    /only be sealed by an approved critic report/,
  )
  assert.throws(() => createSyntheticMasterAsset({ ...base, lineage: [] }), /lineage is required/)
  assert.throws(
    () => createSyntheticMasterAsset({ ...base, lineage: ['generation-1', 'generation-1'] }),
    /lineage entry is duplicated/,
  )
  assert.throws(
    () => createSyntheticMasterAsset({ ...base, scriptHash: digest('7') }),
    /scriptHash does not match/,
  )
})

test('T-FR-104 a tampered master row fails closed instead of being served', () => {
  const master = createSyntheticMasterAsset(base)
  const tampered = { ...master, cost: { ...master.cost, minorUnits: 0 } }
  assert.throws(() => assertSyntheticMasterIntegrity(tampered), /does not match its stored content/)
  assert.notEqual(calculateSyntheticMasterHash(tampered), master.masterHash)

  const relabelled = { ...master, workspaceId: 'workspace-2' }
  assert.throws(() => assertSyntheticMasterIntegrity(relabelled), /does not match its stored content/)
})
