import test from 'node:test';
import assert from 'node:assert/strict';
import { assertProfileEligible, catalogSyntheticMaster, compileSyntheticEditPlan, evaluateSyntheticBlock, prepareAudio, reuseSyntheticBlock, splitSyntheticBlocks, validateHybridStory } from '../../src/v2/domain/synthetic-production.ts';
import { assertProviderContract, ElevenLabsAdapter, FakeAvatarAdapter, FakeTtsAdapter, HeyGenAdapter } from '../../src/v2/infrastructure/synthetic-providers.ts';

const profile = { id: 'ana', version: 2, actor: 'Ana', providerIdentities: { heygen: 'ana-h' }, voiceProfiles: { 'pt-BR': 'ana-v' }, languages: ['pt-BR'], consent: { granted: true, expiresAt: '2030-01-01', allowedLocales: ['pt-BR'], allowedUses: ['ads'], evidenceId: 'consent-1' }, restrictions: [], active: true, disclosure: 'Personagem gerado por IA' };
const audio = prepareAudio({ text: 'Uma frase completa. Outra reflexão.', locale: 'pt-BR' });

test('T-FR-092 produces person-free synthetic presenter edit plan with disclosure', () => { const blocks = splitSyntheticBlocks('Uma frase completa. Outra reflexão.', { audio, profile, providerCapability: 'avatar' }); const plan = compileSyntheticEditPlan({ profile, audio, blocks, broll: ['b1'], captions: true, overlays: ['logo'], use: 'ads' }); assert.equal(plan.hasRealPerson, false); assert.equal(plan.tracks.captions.length, 5); });
test('T-FR-093 validates rights and continuity per block in real-avatar-proof-CTA golden', () => { const result = validateHybridStory([{ id: 'real', kind: 'real', sourceId: '1', rights: true, consent: true, identity: 'ana' }, { id: 'avatar', kind: 'synthetic', sourceId: '2', rights: true, consent: true, identity: 'ana', disclosure: 'IA' }, { id: 'proof', kind: 'proof', sourceId: '3', rights: true, consent: true }, { id: 'cta', kind: 'voiceover', sourceId: '4', rights: true, consent: true }]); assert.deepEqual(result, { allowed: true, issues: [], sequence: 'real>synthetic>proof>voiceover' }); });
test('T-FR-100 accepts text or approved upload and lets audio govern ranges', () => { const uploaded = { ...audio, id: 'approved', approved: true }; assert.equal(prepareAudio({ uploaded, locale: 'pt-BR' }), uploaded); const blocks = splitSyntheticBlocks('Uma frase completa. Outra reflexão.', { audio, profile, providerCapability: 'avatar' }); assert.equal(blocks.at(-1).rangeMs[1], audio.durationMs); });
test('T-FR-101 adapters normalize fake and real provider jobs behind common contracts', async () => { const jobs = [await new FakeTtsAdapter().synthesize({ text: 'oi', locale: 'pt-BR', voiceId: 'a' }), await new FakeAvatarAdapter().generate({ audioUri: 'a', profileId: 'p', durationMs: 1000 }), await new ElevenLabsAdapter(async () => ({ id: 'e', audio: 'a', alignment: 'j', cost: 1 })).synthesize({ text: 'oi', locale: 'pt-BR', voiceId: 'a' }), await new HeyGenAdapter(async () => ({ id: 'h', video: 'v', cost: 2 })).generate({ audioUri: 'a', profileId: 'p', durationMs: 1000 })]; assert.ok(jobs.every(assertProviderContract)); });
test('T-FR-102 stable sentence blocks preserve cache through reorder and isolate failure', () => { const original = splitSyntheticBlocks('Primeira ideia. Segunda ideia.', { audio, profile, providerCapability: 'avatar' }); const reordered = splitSyntheticBlocks('Segunda ideia. Primeira ideia.', { audio, profile, providerCapability: 'avatar' }); assert.deepEqual(new Set(original.map(x => x.cacheKey)), new Set(reordered.map(x => x.cacheKey))); });
test('T-FR-103 blocks expired or incompatible identity and voice cloning', () => { assert.equal(assertProfileEligible(profile, { locale: 'pt-BR', use: 'ads', now: '2029-01-01' }), true); assert.throws(() => assertProfileEligible({ ...profile, consent: { ...profile.consent, granted: false } }, { locale: 'pt-BR', use: 'ads' }), /ineligible/); });
test('T-FR-104 catalogs raw master sentences and reuses without paid regeneration', () => { const blocks = splitSyntheticBlocks('Uma frase completa. Outra reflexão.', { audio, profile, providerCapability: 'avatar' }).map(block => ({ ...block, status: 'ready', artifact: `${block.id}.mp4` })); const asset = { id: 'master', rawVideo: 'raw.mp4', finalAudio: audio, blocks, providerConfig: {}, lineage: ['job'], metadata: { identity: 'ana', outfit: 'blue', scene: 'studio', emotion: 'calm', quality: .95, rights: true } }; assert.equal(catalogSyntheticMaster(asset).length, 2); assert.equal(reuseSyntheticBlock(asset, blocks[0].cacheKey).regenerated, false); });
test('T-FR-105 canonical cache changes only with relevant provider/profile/settings changes', () => { const a = splitSyntheticBlocks('Ideia.', { audio, profile, providerCapability: 'avatar', settings: { quality: 'hd' } })[0]; const b = splitSyntheticBlocks('Ideia.', { audio, profile, providerCapability: 'avatar', settings: { quality: 'hd' } })[0]; const c = splitSyntheticBlocks('Ideia.', { audio, profile, providerCapability: 'avatar', settings: { quality: '4k' } })[0]; assert.equal(a.cacheKey, b.cacheKey); assert.notEqual(a.cacheKey, c.cacheKey); });
test('T-FR-106 critic localizes known failures and chooses retry or fallback', () => { const failure = evaluateSyntheticBlock({ blockId: 'b1', rangeMs: [0, 2000], lipSync: .9, identity: .6, pronunciation: .9, artifacts: .1, framing: .9, continuity: .9 }); assert.equal(failure.passed, false); assert.equal(failure.issue.action, 'fallback'); });
