import {createHash,createHmac,timingSafeEqual} from 'node:crypto';
import {APP_SHELL_DESTINATIONS} from '../domain/app-shell.ts';

export type TraceContext={traceId:string;correlationId:string;workspaceId:string;projectId?:string;jobId?:string};
export function createTraceContext(input:Omit<TraceContext,'traceId'|'correlationId'>):TraceContext{const identity=JSON.stringify(input);return {...input,traceId:createHash('sha256').update(`trace:${identity}`).digest('hex').slice(0,32),correlationId:createHash('sha256').update(`correlation:${identity}`).digest('hex').slice(0,24)};}

export type VerifiedIdentity={subject:string;email:string;provider:'oidc'|'development';verified:boolean};
export type WorkspaceMembership={workspaceId:string;role:'operator'|'director'|'administrator'|'reviewer';status:'active'|'suspended'};
export function issueWorkspaceSession(identity:VerifiedIdentity,membership:WorkspaceMembership,secret:string,now:number,ttlSeconds=3600){if(!identity.verified||membership.status!=='active'||secret.length<32)throw new Error('session-issuance-denied');const payload={sub:identity.subject,email:identity.email,workspaceId:membership.workspaceId,role:membership.role,iat:now,exp:now+ttlSeconds};const encoded=Buffer.from(JSON.stringify(payload)).toString('base64url');const signature=createHmac('sha256',secret).update(encoded).digest('base64url');return {token:`${encoded}.${signature}`,cookie:{httpOnly:true,secure:true,sameSite:'lax' as const,maxAge:ttlSeconds},payload};}
export function verifyWorkspaceSession(token:string,secret:string,now:number){const [encoded,signature]=token.split('.');if(!encoded||!signature)throw new Error('invalid-session');const expected=createHmac('sha256',secret).update(encoded).digest();const supplied=Buffer.from(signature,'base64url');if(supplied.length!==expected.length||!timingSafeEqual(supplied,expected))throw new Error('invalid-session');const payload=JSON.parse(Buffer.from(encoded,'base64url').toString());if(payload.exp<=now)throw new Error('session-expired');return payload;}
export const APP_SHELL_NAVIGATION=APP_SHELL_DESTINATIONS;
export function switchWorkspace(previous:string,next:string){if(previous===next)return {changed:false,invalidate:[],unsubscribe:[]};return {changed:true,invalidate:[`workspace:${previous}:*`],unsubscribe:[`events:${previous}`],subscribe:[`events:${next}`],navigate:'/'};}

export type ClientGovernance={clientId:string;workspaceId:string;delegatedUserId?:string;status:'active'|'suspended'|'revoked';scopes:string[];environment:'development'|'preview'|'production';killSwitch:boolean};
export function authorizeGovernedClient(client:ClientGovernance,input:{workspaceId:string;scope:string}){const reasons=[...(client.workspaceId!==input.workspaceId?['cross-workspace']:[]),...(client.status!=='active'?[client.status]:[]),...(client.killSwitch?['kill-switch']:[]),...(!client.scopes.includes(input.scope)?['scope']:[])];return {allowed:reasons.length===0,reasons,audit:{clientId:client.clientId,workspaceId:client.workspaceId,delegatedUserId:client.delegatedUserId,environment:client.environment}};}

export type GeneralPublicOperation={id:string;projectId?:string;type:'ingest'|'director'|'provider'|'sync'|'batch'|'render'|'export';status:'queued'|'running'|'waiting'|'retrying'|'cancelled'|'failed'|'dead-letter'|'completed';phase:string;completedUnits?:number;totalUnits?:number;cost?:number;result?:{artifactId:string};error?:{code:string;message:string};retryable:boolean;cancelable:boolean};
export function presentPublicOperation(op:GeneralPublicOperation){return {...op,progress:op.totalUnits?Math.round(100*(op.completedUnits??0)/op.totalUnits):undefined,indeterminate:!op.totalUnits&&!['completed','failed','cancelled','dead-letter'].includes(op.status),sensitiveDiagnostics:undefined};}
export function enqueuePublicOperation(type:GeneralPublicOperation['type'],projectId:string|undefined,idempotencyKey:string):GeneralPublicOperation{return {id:`op-${createHash('sha256').update(`${type}:${projectId}:${idempotencyKey}`).digest('hex').slice(0,16)}`,projectId,type,status:'queued',phase:'accepted',retryable:true,cancelable:true};}

export type FoundationOutboxEvent={id:string;workspaceId:string;resourceId:string;type:string;version:number;occurredAt:string;sequence:number;payload:Record<string,unknown>};
export function createTransitionOutbox(input:Omit<FoundationOutboxEvent,'id'>){const id=`evt-${createHash('sha256').update(JSON.stringify(input)).digest('hex').slice(0,20)}`;return {...input,id,transactional:true,delivery:'at-least-once' as const};}
