import {createHash} from 'node:crypto';
export type IdempotentEffect<T>={scope:string;key:string;fingerprint:string;status:'started'|'completed';result?:T};
export class EffectLedger<T>{private rows=new Map<string,IdempotentEffect<T>>();execute(scope:string,key:string,request:unknown,effect:()=>T){const id=`${scope}:${key}`,fingerprint=createHash('sha256').update(JSON.stringify(request)).digest('hex'),existing=this.rows.get(id);if(existing){if(existing.fingerprint!==fingerprint)throw new Error('idempotency-conflict');return {replayed:true,result:existing.result}}this.rows.set(id,{scope,key,fingerprint,status:'started'});const result=effect();this.rows.set(id,{scope,key,fingerprint,status:'completed',result});return {replayed:false,result}}size(){return this.rows.size}}
export const IDEMPOTENCY_SCOPES=['upload','command','workflow-step','provider-submit','render','callback'] as const;

export type DurableCheckpoint={workflowId:string;phase:'ingest'|'perception'|'director'|'provider'|'render'|'batch';status:'before-effect'|'after-effect';artifactId?:string;heartbeatAt:string};
export function reconcileWorkflows(checkpoints:DurableCheckpoint[],now:string,staleMs:number){const time=new Date(now).getTime();return checkpoints.map(cp=>{const stale=time-new Date(cp.heartbeatAt).getTime()>staleMs;return {...cp,reconciled:stale,action:stale?(cp.status==='after-effect'&&cp.artifactId?'verify-and-resume':'retry-from-checkpoint'):'continue'}});}

const SENSITIVE_KEYS=/prompt|transcript|url|email|phone|face|voice|secret|token|credential/i;
export function redactTelemetry(input:Record<string,unknown>){return Object.fromEntries(Object.entries(input).map(([key,value])=>[key,SENSITIVE_KEYS.test(key)?'[REDACTED]':value]));}
export function telemetryEvent(input:{context:{workspaceId:string;projectId?:string;versionId?:string;runId?:string;workflowId?:string;providerJobId?:string;traceId:string};metrics:{durationMs:number;waitMs:number;attempts:number;bytes:number;tokens:number;estimatedCost:number;actualCost:number};data?:Record<string,unknown>;status:string}){return {...input,data:redactTelemetry(input.data??{}),hardInvariantAlert:['rights-bypass','duplicate-effect','artifact-hash-mismatch'].includes(input.status)};}

export type ReplayManifest={schemaVersion:number;planHash:string;propsHash:string;assetHashes:string[];toolVersions:Record<string,string>;modelVersions:Record<string,string>;seeds:Record<string,number>;providerConfig:Record<string,unknown>;fonts:string[];luts:string[];rendererPackage:string;determinism:'deterministic'|'best-effort'};
export function replayArtifact(manifest:ReplayManifest,input:{isolated:boolean;available:Set<string>;actual:{videoHash?:string;expectedVideoHash?:string;visualDistance:number;audioDistance:number};tolerance:{visual:number;audio:number}}){const required=[...manifest.assetHashes,...manifest.fonts,...manifest.luts,manifest.rendererPackage];const missing=required.filter(x=>!input.available.has(x));const deterministic=manifest.determinism==='deterministic';const exact=deterministic&&input.actual.videoHash===input.actual.expectedVideoHash;const withinTolerance=input.actual.visualDistance<=input.tolerance.visual&&input.actual.audioDistance<=input.tolerance.audio;return {allowed:input.isolated&&!missing.length,missing,passed:!missing.length&&(exact||withinTolerance),mode:manifest.determinism};}

export const PERFORMANCE_BUDGETS={shellP95Ms:1500,metadataP95Ms:800,firstFrameP95Ms:1200,seekP95Ms:250,timelineInputP95Ms:50,commandP95Ms:300} as const;
export function evaluatePerformance(samples:Record<string,number[]>,projectClass:'small'|'medium'|'1000-clips'|'long-form'){const metrics=Object.fromEntries(Object.entries(samples).map(([name,values])=>{const sorted=[...values].sort((a,b)=>a-b),p=(q:number)=>sorted[Math.min(sorted.length-1,Math.floor(sorted.length*q))]??0;return [name,{p50:p(.5),p95:p(.95)}]}));const regressions=Object.entries(metrics).filter(([name,value])=>{const key=`${name}P95Ms` as keyof typeof PERFORMANCE_BUDGETS;return PERFORMANCE_BUDGETS[key]!==undefined&&value.p95>PERFORMANCE_BUDGETS[key]}).map(([name])=>name);return {projectClass,metrics,passed:!regressions.length,regressions,previewUsesProxy:true,heavyWorkInWorkers:true,virtualize:['timeline','library'],degradeFirst:'thumbnails'};}

export type QueueClass='ingest'|'perception'|'director'|'provider'|'render'|'batch'|'export'|'localization'|'callback';
export function scheduleWork(input:{queue:QueueClass;workspaceId:string;priority:number;queued:number;running:number;concurrency:number;quota:number;fanout:number;preflightApproved:boolean;workerCostPerHour:number}){const blocked=input.running>=input.concurrency?'backpressure':input.running+input.queued>=input.quota?'workspace-quota':input.fanout>1&&!input.preflightApproved?'preflight-required':undefined;return {accepted:!blocked,blocked,autoscaleTarget:Math.min(input.concurrency,Math.ceil(input.queued/5)),workerClass:`${input.queue}-worker`,estimatedHourlyCost:input.workerCostPerHour*Math.max(1,Math.ceil(input.queued/5))};}

export function securityGate(input:{secretRefsOnly:boolean;workspaceAuthorized:boolean;signedUrlTtlSeconds:number;mimeValid:boolean;quarantinePassed:boolean;ssrfProtected:boolean;webhookVerified:boolean;apiAuthenticated:boolean;syntheticAudit:boolean;threatModelCurrent:boolean}){const checks={...input,shortSignedUrl:input.signedUrlTtlSeconds<=300};return {passed:Object.values(checks).every(Boolean),checks};}
export type PrivacyAsset={id:string;kind:'asset'|'face'|'voice'|'consent'|'testimonial'|'transcript'|'segment'|'artifact'|'cache';sensitive:boolean;dependsOn:string[];retentionUntil?:string};
export function planPrivacyDeletion(assets:PrivacyAsset[],sourceId:string){const deleted=new Set([sourceId]);let changed=true;while(changed){changed=false;for(const asset of assets)if(!deleted.has(asset.id)&&asset.dependsOn.some(x=>deleted.has(x))){deleted.add(asset.id);changed=true}}return {sourceId,tombstone:`tombstone:${sourceId}`,deleteIds:[...deleted],audit:{purpose:'verified-deletion',traceable:true},analyticsPayload:{sourceId:createHash('sha256').update(sourceId).digest('hex').slice(0,12),content:undefined}};}
export function privacyExport(assets:PrivacyAsset[],authorizedIds:Set<string>){return {schemaVersion:1,records:assets.filter(x=>authorizedIds.has(x.id)).map(x=>({id:x.id,kind:x.kind,sensitive:x.sensitive,retentionUntil:x.retentionUntil})),contentLocations:[]};}

export type VersionedSchema={kind:'database'|'event'|'edit-plan'|'manifest'|'provider-result'|'embedding';version:number;readableVersions:number[];migrate:(value:any)=>any};
export function readVersioned(schema:VersionedSchema,value:{version:number;data:unknown}){if(!schema.readableVersions.includes(value.version))throw new Error(`unsupported-${schema.kind}-version:${value.version}`);return value.version===schema.version?value:{version:schema.version,data:schema.migrate(value.data)};}

export const TEST_FIXTURE_FAMILIES=['timing','sync','claims','layout','color','audio','localization'] as const;
export const FAKE_ADAPTERS=['storage','models','providers','workflow','renderer'] as const;
export function riskCoverage(input:{risk:string;tests:string[];goldenReviewed:boolean;e2eJourney?:string}[]){const uncovered=input.filter(x=>!x.tests.length||!x.goldenReviewed);return {passed:!uncovered.length,uncovered,journeys:new Set(input.flatMap(x=>x.e2eJourney?[x.e2eJourney]:[])).size,metric:'risk-coverage-not-line-percentage'};}

export function externalParity(input:{capabilityId:string;uiResult:unknown;restResult:unknown;mcpResult:unknown;schemaRef:string;version:string;activeClients:number;deprecated?:{sunsetAt:string;guide:string}}[]){const divergent=input.filter(x=>JSON.stringify(x.uiResult)!==JSON.stringify(x.restResult)||JSON.stringify(x.restResult)!==JSON.stringify(x.mcpResult));const invalidSunset=input.filter(x=>x.deprecated&&(!x.deprecated.guide||x.activeClients>0&&new Date(x.deprecated.sunsetAt)<=new Date()));return {passed:!divergent.length&&!invalidSunset.length,divergent:divergent.map(x=>x.capabilityId),invalidSunset:invalidSunset.map(x=>x.capabilityId),singleSource:true,stableErrorsWithinMajor:true};}
