import {createHash,createHmac,timingSafeEqual} from 'node:crypto';

export const FOUNDATION_INFRA={database:{engine:'postgresql',version:'16',isolated:true},objectStorage:{protocol:'s3-compatible',development:'minio',masterBucket:'apollo-masters',derivativeBucket:'apollo-derivatives'},workflow:{store:'postgresql',durable:true,checkpointed:true},renderer:{remotion:'4.0.489',ffmpeg:'8'},web:{next:'16.2.10',react:'19.2.7'},vector:{engine:'pgvector',embeddingVersion:'v1'}} as const;
export function foundationSeeds(workspaceId='workspace-demo'){return {workspace:{id:workspaceId,name:'Apollo Demo'},project:{id:'project-demo',workspaceId,name:'Primeiro vídeo',status:'draft'},source:{id:'source-demo',workspaceId,kind:'video',state:'ready'},outputSpec:{id:'vertical-1080',aspectRatio:'9:16',width:1080,height:1920,fps:30}};}
export type TraceContext={traceId:string;correlationId:string;workspaceId:string;projectId?:string;jobId?:string};
export function createTraceContext(input:Omit<TraceContext,'traceId'|'correlationId'>):TraceContext{const identity=JSON.stringify(input);return {...input,traceId:createHash('sha256').update(`trace:${identity}`).digest('hex').slice(0,32),correlationId:createHash('sha256').update(`correlation:${identity}`).digest('hex').slice(0,24)};}
export function runFoundationSmoke(input:{workspaceId:string;sourceChecksum:string;recipeVersion:string;planHash:string;outputSpecId:string}){const trace=createTraceContext({workspaceId:input.workspaceId,projectId:'smoke-project',jobId:'smoke-render'});const normalizedChecksum=createHash('sha256').update(`${input.sourceChecksum}:${input.recipeVersion}`).digest('hex');const manifest={schemaVersion:1,sourceChecksum:input.sourceChecksum,normalizedChecksum,recipeVersion:input.recipeVersion,planHash:input.planHash,outputSpecId:input.outputSpecId};const proxyChecksum=createHash('sha256').update(JSON.stringify(manifest)).digest('hex');return {trace,stages:['upload','verify','normalize','plan','render','verify-output'],manifest,proxy:{checksum:proxyChecksum,canonicalKey:`proxy/${proxyChecksum}.mp4`},reconstructable:true};}

export type VerifiedIdentity={subject:string;email:string;provider:'oidc'|'development';verified:boolean};
export type WorkspaceMembership={workspaceId:string;role:'operator'|'director'|'administrator'|'reviewer';status:'active'|'suspended'};
export function issueWorkspaceSession(identity:VerifiedIdentity,membership:WorkspaceMembership,secret:string,now:number,ttlSeconds=3600){if(!identity.verified||membership.status!=='active'||secret.length<32)throw new Error('session-issuance-denied');const payload={sub:identity.subject,email:identity.email,workspaceId:membership.workspaceId,role:membership.role,iat:now,exp:now+ttlSeconds};const encoded=Buffer.from(JSON.stringify(payload)).toString('base64url');const signature=createHmac('sha256',secret).update(encoded).digest('base64url');return {token:`${encoded}.${signature}`,cookie:{httpOnly:true,secure:true,sameSite:'lax' as const,maxAge:ttlSeconds},payload};}
export function verifyWorkspaceSession(token:string,secret:string,now:number){const [encoded,signature]=token.split('.');if(!encoded||!signature)throw new Error('invalid-session');const expected=createHmac('sha256',secret).update(encoded).digest();const supplied=Buffer.from(signature,'base64url');if(supplied.length!==expected.length||!timingSafeEqual(supplied,expected))throw new Error('invalid-session');const payload=JSON.parse(Buffer.from(encoded,'base64url').toString());if(payload.exp<=now)throw new Error('session-expired');return payload;}
export const APP_SHELL_NAVIGATION=[{id:'projects',href:'/'},{id:'batches',href:'/batches'},{id:'library',href:'/assets'},{id:'presenters',href:'/settings?tab=presenters'},{id:'brand',href:'/settings?tab=brand'},{id:'settings',href:'/settings'}] as const;
export function switchWorkspace(previous:string,next:string){if(previous===next)return {changed:false,invalidate:[],unsubscribe:[]};return {changed:true,invalidate:[`workspace:${previous}:*`],unsubscribe:[`events:${previous}`],subscribe:[`events:${next}`],navigate:'/'};}

export const ARCHITECTURE_LAYERS={web:['application','domain','public-api'],application:['domain'],domain:[],infrastructure:['application','domain'],worker:['application','infrastructure'],renderer:['render-input'],provider:['application','domain'],critic:['domain']} as const;
export function validateArchitectureImport(from:keyof typeof ARCHITECTURE_LAYERS,to:string){return {allowed:(ARCHITECTURE_LAYERS[from] as readonly string[]).includes(to),from,to};}
export function runFakeVerticalFlow(){return ['web-query','application-auth','domain-command','orchestrator','provider-fake','critic','compiler','renderer'] as const;}

export const CONCEPTUAL_AGGREGATES={Workspace:['Workspace','WorkspaceMember','BrandKit','PolicySnapshot'],Project:['Project','ProjectVersion','EditCommand','EditPlan','OutputSpec'],Media:['SourceAsset','DerivativeAsset','SpeechSegment','EvidenceSegment'],Capture:['CaptureSession','CaptureTrack','SyncDiagnostic'],Synthetic:['SyntheticPresenterProfile','SyntheticMasterAsset','ProviderJob'],Execution:['PublicOperation','DirectorRun','QualityReport','ArtifactManifest']} as const;
export const UI_CAPABILITIES=[{action:'project:create',capabilityId:'projects.create',endpoint:'/v1/projects',test:'public-project-api'},{action:'project:list',capabilityId:'projects.list',endpoint:'/v1/projects',test:'public-project-api'},{action:'render:start',capabilityId:'artifacts.renders.create',endpoint:'/v1/artifacts/{artifactId}/renders/{manifestId}',test:'remotion-renderer'},{action:'operation:cancel',capabilityId:'operations.cancel',endpoint:'/v1/operations/{operationId}/cancel',test:'public-operation-worker'},{action:'operation:retry',capabilityId:'operations.retry',endpoint:'/v1/operations/{operationId}/retry',test:'public-operation-worker'}] as const;
export const INTERNAL_ONLY=['database-row','storage-location','render-input-plaintext','provider-credential','raw-prompt','worker-lease-token'] as const;
export function capabilityParityReport(items:{action:string;capabilityId?:string;endpoint?:string;test?:string;internalReason?:string}[]){const missing=items.filter(x=>!(x.capabilityId&&x.endpoint&&x.test)&&!x.internalReason);return {passed:missing.length===0,missing,rows:items};}

export const PUBLIC_CONVENTIONS={version:'/v1',id:'opaque-string',date:'RFC3339 UTC',frame:'non-negative integer in declared fps',pagination:'opaque cursor bound to workspace and filters',filters:'allowlisted',json:'application/json; charset=utf-8'} as const;
export function deprecationHeaders(input:{deprecatedAt:string;sunsetAt:string;guide:string}){return {Deprecation:input.deprecatedAt,Sunset:input.sunsetAt,Link:`<${input.guide}>; rel="deprecation"`};}

export type ClientGovernance={clientId:string;workspaceId:string;delegatedUserId?:string;status:'active'|'suspended'|'revoked';scopes:string[];environment:'development'|'preview'|'production';killSwitch:boolean};
export function authorizeGovernedClient(client:ClientGovernance,input:{workspaceId:string;scope:string}){const reasons=[...(client.workspaceId!==input.workspaceId?['cross-workspace']:[]),...(client.status!=='active'?[client.status]:[]),...(client.killSwitch?['kill-switch']:[]),...(!client.scopes.includes(input.scope)?['scope']:[])];return {allowed:reasons.length===0,reasons,audit:{clientId:client.clientId,workspaceId:client.workspaceId,delegatedUserId:client.delegatedUserId,environment:client.environment}};}

export type GeneralPublicOperation={id:string;projectId?:string;type:'ingest'|'director'|'provider'|'sync'|'batch'|'render'|'export';status:'queued'|'running'|'waiting'|'retrying'|'cancelled'|'failed'|'dead-letter'|'completed';phase:string;completedUnits?:number;totalUnits?:number;cost?:number;result?:{artifactId:string};error?:{code:string;message:string};retryable:boolean;cancelable:boolean};
export function presentPublicOperation(op:GeneralPublicOperation){return {...op,progress:op.totalUnits?Math.round(100*(op.completedUnits??0)/op.totalUnits):undefined,indeterminate:!op.totalUnits&&!['completed','failed','cancelled','dead-letter'].includes(op.status),sensitiveDiagnostics:undefined};}
export function enqueuePublicOperation(type:GeneralPublicOperation['type'],projectId:string|undefined,idempotencyKey:string):GeneralPublicOperation{return {id:`op-${createHash('sha256').update(`${type}:${projectId}:${idempotencyKey}`).digest('hex').slice(0,16)}`,projectId,type,status:'queued',phase:'accepted',retryable:true,cancelable:true};}

export type FoundationOutboxEvent={id:string;workspaceId:string;resourceId:string;type:string;version:number;occurredAt:string;sequence:number;payload:Record<string,unknown>};
export function createTransitionOutbox(input:Omit<FoundationOutboxEvent,'id'>){const id=`evt-${createHash('sha256').update(JSON.stringify(input)).digest('hex').slice(0,20)}`;return {...input,id,transactional:true,delivery:'at-least-once' as const};}
