export const PHASE_GATES=['F0','F1','F2','F3','F4','F5'] as const;
export function canReleasePhase(phase:typeof PHASE_GATES[number],approved:Set<string>){const index=PHASE_GATES.indexOf(phase);return {allowed:PHASE_GATES.slice(0,index).every(x=>approved.has(x)),missing:PHASE_GATES.slice(0,index).filter(x=>!approved.has(x))};}
export const REFERENCE_DATASETS=[{id:'discovery-talking-9x16',objective:'discovery',mode:'talking-head',format:'9:16',humanSampleRate:.1,rubricVersion:'1'},{id:'conversion-voiceover-16x9',objective:'sale',mode:'voiceover',format:'16:9',humanSampleRate:.2,rubricVersion:'1'}] as const;
export function costRiskGate(input:{preflight:boolean;reserved:number;runCap:number;workspaceSpent:number;workspaceCap:number;cacheChecked:boolean;deduped:boolean;topN:number;requested:number}){const reasons=[...(!input.preflight?['preflight']:[]),...(!input.cacheChecked?['cache']:[]),...(!input.deduped?['dedupe']:[]),...(input.reserved>input.runCap?['run-cap']:[]),...(input.workspaceSpent+input.reserved>input.workspaceCap?['workspace-cap']:[]),...(input.requested>input.topN?['top-n']:[])];return {allowed:!reasons.length,reasons,anomaly:reasons.some(x=>x.endsWith('cap'))};}
export function providerRisk(input:{contractPassed:boolean;healthy:boolean;circuitOpen:boolean;current:{capability:string;price:number;limit:number;version:string};previous?:{capability:string;price:number;limit:number;version:string};fallbackAvailable:boolean}){const changed=input.previous&&JSON.stringify(input.previous)!==JSON.stringify(input.current);return {available:input.contractPassed&&input.healthy&&!input.circuitOpen,changed,requiresReview:Boolean(changed),fallback:!input.healthy||input.circuitOpen?input.fallbackAvailable:false};}
export function integrityRisk(input:{before:boolean;afterReorder:boolean;afterTrim:boolean;afterLocalization:boolean;qualifiers:boolean;dependencies:boolean}){return {passed:Object.values(input).every(Boolean),humanReview:!Object.values(input).every(Boolean)};}
export function libraryGovernance(input:{checksum:boolean;rights:boolean;metadataTier:boolean;workspaceScoped:boolean;lifecycle:boolean;duplicates:number;unknown:number;unused:number}){return {passed:input.checksum&&input.rights&&input.metadataTier&&input.workspaceScoped&&input.lifecycle,metrics:{duplicates:input.duplicates,unknown:input.unknown,unused:input.unused},actions:['review-unknown','archive-unused','verified-delete']};}
export function storageGarbageCollection(input:{assets:{id:string;class:'master'|'derivative'|'temp';ageDays:number;reconstructable:boolean;references:string[]}[];quotas:{master:number;derivative:number;temp:number};retention:{master:number;derivative:number;temp:number}}){const referenced=new Set(input.assets.flatMap(x=>x.references));return input.assets.map(asset=>({id:asset.id,eligible:!referenced.has(asset.id)&&asset.ageDays>input.retention[asset.class]&&(asset.class==='temp'||asset.class==='derivative'&&asset.reconstructable),reason:referenced.has(asset.id)?'referenced':asset.class==='master'?'master-retained':'age-and-reconstructability'}));}
export function automationAbuseRisk(input:{requestsPerMinute:number;mutationsPerMinute:number;generationSpend:number;downloadsGb:number;limits:{requests:number;mutations:number;spend:number;downloadsGb:number};scopesMinimal:boolean;credentialRevocable:boolean;killSwitch:boolean}){const anomalies=[...(input.requestsPerMinute>input.limits.requests?['request-loop']:[]),...(input.mutationsPerMinute>input.limits.mutations?['mutation-loop']:[]),...(input.generationSpend>input.limits.spend?['generation-spend']:[]),...(input.downloadsGb>input.limits.downloadsGb?['download-exfiltration']:[])];return {allowed:!anomalies.length&&input.scopesMinimal&&input.credentialRevocable&&!input.killSwitch,anomalies,action:anomalies.length?'suspend-client-and-investigate':'continue'};}

export const V1_REUSE_INVENTORY=[
  {module:'remotion/scenes',reuse:'adapt',contract:'RenderInput v2 props only',owner:'renderer',hidden:['global composition defaults']},
  {module:'remotion/subtitles',reuse:'adapt',contract:'SubtitleStylePreset',owner:'editor',hidden:['font availability']},
  {module:'src/lib/services/ffmpeg.ts',reuse:'extract',contract:'versioned recipe + durable job',owner:'media',hidden:['filesystem staging']},
  {module:'src/lib/services/whisper.ts',reuse:'extract',contract:'TranscriptionAdapter',owner:'perception',hidden:['provider word timing']},
  {module:'src/lib/services/remotion-render.ts',reuse:'replace',contract:'RenderInput renderer port',owner:'renderer',hidden:['watchdog/locks']},
  {module:'src/lib/services/image-generation.ts',reuse:'adapt',contract:'Provider Registry',owner:'providers',hidden:['vendor payload']},
  {module:'src/lib/services/stock-video.ts',reuse:'adapt',contract:'Asset Provider',owner:'providers',hidden:['license assumptions']},
  {module:'src/lib/services/claude.ts',reuse:'replace',contract:'Director/tools/policy/model routing',owner:'director',hidden:['monolithic prompt state']},
] as const;
export function evaluateV1Extraction(input:{module:string;characterizationTests:string[];v2ContractTests:string[];directV1Imports:number;extractionCost:number;replacementCost:number;bridgeTemporary:boolean}){const accepted=input.characterizationTests.length>0&&input.v2ContractTests.length>0&&input.directV1Imports===0&&input.extractionCost<=input.replacementCost;return {accepted,reason:accepted?'contract-extraction':input.directV1Imports?'incompatible-coupling':'replacement-preferred',deleteBridge:accepted&&input.bridgeTemporary,origin:input.module};}

export const RELEASE_DECISIONS={
  beforeF1:{permissions:'role matrix ADR-010/012',autoApply:{minimumConfidence:.9,hardGatesNeverAuto:true},firstProxyTargets:{under15min:300,under60min:900,over60min:'progressive'},retention:{master:'project lifetime + 90d',derivative:'30d if reconstructable',temp:'24h'},externalAuth:'service keys now; OAuth 2.1 for delegated users',apiSupport:'major + 180d sunset',webhooks:{ordering:'per-resource',retentionDays:90,replayDays:30},limits:{requestsPerMinute:120,costPerRun:100,costPerWorkspaceDay:1000},mcp:{tools:['projects.list','projects.create','operations.read','operations.cancel','operations.retry','artifacts.render'],preflight:['artifacts.render']}},
  beforeF2:{batchDefault:6,batchMax:50,validatedHook:'external performance source + scope + date; historical only',urlImport:'disabled until platform terms adapter',librarySharing:'strict workspace isolation',lutStock:'license and provenance required'},
  beforeF3:{providers:['fake contract adapter','HeyGen','ElevenLabs','Higgsfield pilot after contract suite'],syntheticDisclosure:'market/channel policy; visible when required'},
  beforeF5:{soundLicense:'owned or catalog license with territory/channel/expiry evidence',loudness:{socialLufs:-14,broadcastLufs:-23,truePeakDb:-1,localeProfiles:true}},
} as const;
export function validateReleaseDecisionRecord(input:{owner:string;due:string;options:string[];evidence:string[];impact:string;adr:string;configVersion:number;tests:string[]}){const missing=Object.entries(input).filter(([key,value])=>key==='configVersion'?Number(value)<1:Array.isArray(value)?!value.length:!value).map(([key])=>key);return {valid:!missing.length,missing};}
