import type { MusicMontageRun } from '../application/ports/music-led-montage.ts'
import { DomainError } from '../domain/errors.ts'
import { resolveStrategicObjective } from '../domain/strategic-objective.ts'

function record(value: unknown, field: string): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new DomainError('INVALID_ARGUMENT', `${field} must be an object`); return value as Record<string, unknown> }
function exact(value: Record<string, unknown>, allowed: readonly string[], field: string): void { const fields = Object.keys(value).filter((key) => !allowed.includes(key)); if (fields.length) throw new DomainError('INVALID_ARGUMENT', `${field} contains unknown fields`, { fields }) }
function string(value: unknown, field: string, minimum = 1, maximum = 128): string { if (typeof value !== 'string' || value.trim().length < minimum || value.trim().length > maximum) throw new DomainError('INVALID_ARGUMENT', `${field} must contain ${minimum} to ${maximum} characters`); return value.trim() }
function numeric(value: unknown, field: string, minimum: number, maximum: number, integer = false): number { if (typeof value !== 'number' || !Number.isFinite(value) || value < minimum || value > maximum || (integer && !Number.isSafeInteger(value))) throw new DomainError('INVALID_ARGUMENT', `${field} must be ${integer ? 'an integer' : 'a number'} between ${minimum} and ${maximum}`); return value }

export function parseMusicMontageBody(raw: unknown) {
  const body = record(raw, 'body')
  exact(body, ['projectVersionId', 'analysisId', 'locale', 'market', 'objective', 'fps', 'sources', 'visualSegments', 'minimumConfidence', 'maximumSnapDistanceMs', 'minimumCutSpacingMs', 'maximumCutsPer10s'], 'body')
  if (!Array.isArray(body.sources) || body.sources.length < 1 || body.sources.length > 100) throw new DomainError('INVALID_ARGUMENT', 'sources must contain 1 to 100 entries')
  if (!Array.isArray(body.visualSegments) || body.visualSegments.length < 1 || body.visualSegments.length > 1000) throw new DomainError('INVALID_ARGUMENT', 'visualSegments must contain 1 to 1000 entries')
  const sources = body.sources.map((entry, index) => { const source = record(entry, `sources[${index}]`); exact(source, ['id', 'artifactId', 'durationSeconds'], `sources[${index}]`); return Object.freeze({ id: string(source.id, `sources[${index}].id`, 3), artifactId: string(source.artifactId, `sources[${index}].artifactId`, 3), durationSeconds: numeric(source.durationSeconds, `sources[${index}].durationSeconds`, 0.001, 86_400) }) })
  const visualSegments = body.visualSegments.map((entry, index) => { const segment = record(entry, `visualSegments[${index}]`); exact(segment, ['id', 'sourceId', 'sourceArtifactId', 'sourceRangeMs', 'preferredDurationMs'], `visualSegments[${index}]`); if (!Array.isArray(segment.sourceRangeMs) || segment.sourceRangeMs.length !== 2) throw new DomainError('INVALID_ARGUMENT', `visualSegments[${index}].sourceRangeMs must contain exactly two integers`); const start = numeric(segment.sourceRangeMs[0], `visualSegments[${index}].sourceRangeMs[0]`, 0, 86_400_000, true); const end = numeric(segment.sourceRangeMs[1], `visualSegments[${index}].sourceRangeMs[1]`, 1, 86_400_000, true); if (end <= start) throw new DomainError('INVALID_ARGUMENT', `visualSegments[${index}].sourceRangeMs must increase`); return Object.freeze({ id: string(segment.id, `visualSegments[${index}].id`, 3), sourceId: string(segment.sourceId, `visualSegments[${index}].sourceId`, 3), sourceArtifactId: string(segment.sourceArtifactId, `visualSegments[${index}].sourceArtifactId`, 3), sourceRangeMs: Object.freeze([start, end] as [number, number]), preferredDurationMs: numeric(segment.preferredDurationMs, `visualSegments[${index}].preferredDurationMs`, 1, end - start, true) }) })
  let locale: string; try { locale = Intl.getCanonicalLocales(string(body.locale, 'locale', 2, 35))[0]! } catch { throw new DomainError('INVALID_ARGUMENT', 'locale must be a valid locale') }
  return Object.freeze({ projectVersionId: string(body.projectVersionId, 'projectVersionId', 3), analysisId: string(body.analysisId, 'analysisId', 3), locale, objective: resolveStrategicObjective(string(body.objective, 'objective')).id, fps: body.fps === undefined ? 30 : numeric(body.fps, 'fps', 1, 120, true), sources: Object.freeze(sources), visualSegments: Object.freeze(visualSegments), ...(body.market !== undefined ? { market: string(body.market, 'market', 2, 16) } : {}), ...(body.minimumConfidence !== undefined ? { minimumConfidence: numeric(body.minimumConfidence, 'minimumConfidence', 0, 1) } : {}), ...(body.maximumSnapDistanceMs !== undefined ? { maximumSnapDistanceMs: numeric(body.maximumSnapDistanceMs, 'maximumSnapDistanceMs', 0, 10_000, true) } : {}), ...(body.minimumCutSpacingMs !== undefined ? { minimumCutSpacingMs: numeric(body.minimumCutSpacingMs, 'minimumCutSpacingMs', 0, 60_000, true) } : {}), ...(body.maximumCutsPer10s !== undefined ? { maximumCutsPer10s: numeric(body.maximumCutsPer10s, 'maximumCutsPer10s', 1, 100, true) } : {}) })
}

/** Deliberately exposes only the content-addressed domain result, never storage or actor-audit columns. */
export function presentMusicMontageRun(run: Readonly<MusicMontageRun>) { return run }
