export type AudioSyncMode='narrative-led'|'music-led'|'hybrid';
export function chooseAudioSyncMode(input:{requested?:AudioSyncMode;speechImportance:number;beatConfidence:number;musicIsPrimary:boolean}){const mode=input.requested??(input.musicIsPrimary&&input.beatConfidence>=.75&&input.speechImportance<.7?'music-led':input.beatConfidence>=.65?'hybrid':'narrative-led');return {mode,priority:mode==='music-led'?'beat':mode==='narrative-led'?'speech':'speech-with-beat-opportunities',snapToleranceMs:mode==='music-led'?120:mode==='hybrid'?80:0,reason:`speech:${input.speechImportance};beat:${input.beatConfidence};primary:${input.musicIsPrimary}`};}
export type AudioEvent={id:string;kind:'music'|'sfx'|'stinger'|'room-tone'|'speech';rangeMs:[number,number];sourceId:string;gainDb:number;group:string;protected?:boolean;snap?:'beat'|'none'};
export type AudioDirectionPlan={version:number;mode:AudioSyncMode;musicSections:{id:string;rangeMs:[number,number];energy:number}[];beatGridMs:number[];events:AudioEvent[];transitions:{atMs:number;kind:'cut'|'crossfade';durationMs:number}[];ducking:{speechTrack:string;musicTrack:string;reductionDb:number;attackMs:number;releaseMs:number};mix:{speechLufs:number;musicLufs:number;sfxLufs:number;roomToneLufs:number;targetLufs:number;truePeakDb:number};overrides:{rangeMs:[number,number];values:Partial<AudioEvent>}[]};
export function compileAudioDirectionPlan(plan:AudioDirectionPlan){const events=[...plan.events].sort((a,b)=>a.rangeMs[0]-b.rangeMs[0]||a.id.localeCompare(b.id)).map(event=>{const override=plan.overrides.find(x=>event.rangeMs[0]>=x.rangeMs[0]&&event.rangeMs[1]<=x.rangeMs[1]);return event.protected?event:{...event,...override?.values}});return {schemaVersion:1,mode:plan.mode,tracks:{events,transitions:plan.transitions,automation:{ducking:plan.ducking},master:plan.mix},beatGridMs:plan.beatGridMs,manifestReason:`${plan.mode}:${events.length}:${plan.beatGridMs.length}`};}

export type SoundAsset={id:string;kind:'music'|'sfx'|'stinger'|'room-tone';bpm?:number;key?:string;mood:string[];durationMs:number;rights:{territories:string[];channels:string[];expiresAt?:string};metadata:{version:number;waveform:number[];loudnessLufs:number;truePeakDb:number;beatGridMs:number[];sections:{rangeMs:[number,number];energy:number}[]};function:string;energy:number;theme:string[]};
export function searchSoundLibrary(assets:SoundAsset[],input:{function:string;energy:number;theme:string[];territory:string;channel:string;now:string}){return assets.map(asset=>{const expired=asset.rights.expiresAt&&new Date(asset.rights.expiresAt)<=new Date(input.now);const eligible=asset.rights.territories.includes(input.territory)&&asset.rights.channels.includes(input.channel)&&!expired;const score=(asset.function===input.function?1:0)+(1-Math.abs(asset.energy-input.energy))+input.theme.filter(x=>asset.theme.includes(x)).length*.5;return {asset,eligible,score,reasons:eligible?[]:['rights']}}).filter(x=>x.eligible).sort((a,b)=>b.score-a.score);}

export function applySoundBudget(events:AudioEvent[],input:{windowMs:number;maxDensity:number;cooldownMs:number;maxIntensity:number;intensityByKind:Record<string,number>}){const accepted:AudioEvent[]=[];const removed:{event:AudioEvent;reason:string}[]=[];for(const event of [...events].sort((a,b)=>a.rangeMs[0]-b.rangeMs[0])){if(event.kind==='speech'||event.kind==='room-tone'){accepted.push(event);continue}const nearby=accepted.filter(x=>x.kind!=='speech'&&x.rangeMs[0]>=event.rangeMs[0]-input.windowMs);const repeated=nearby.some(x=>x.group===event.group&&event.rangeMs[0]-x.rangeMs[0]<input.cooldownMs);const intensity=nearby.reduce((s,x)=>s+(input.intensityByKind[x.kind]??0),0)+(input.intensityByKind[event.kind]??0);const reason=repeated?'repetition-cooldown':nearby.length>=input.maxDensity?'density':intensity>input.maxIntensity?'intensity':undefined;if(reason)removed.push({event,reason});else accepted.push(event)}const consumption=accepted.filter(x=>x.kind!=='speech'&&x.kind!=='room-tone').length/input.maxDensity;return {accepted,removed,consumption,tone:consumption<.4?'sober':consumption<=1?'adequate':'exaggerated'};}

export function mixAndMaster(input:{events:AudioEvent[];speechRanges:[number,number][];targetLufs:number;truePeakDb:number;destination:string;sampleRate:number}){const automation=input.events.map(event=>{const overlapsSpeech=input.speechRanges.some(([s,e])=>event.rangeMs[0]<e&&event.rangeMs[1]>s);const gainDb=event.kind==='music'&&overlapsSpeech?event.gainDb-8:event.gainDb;return {eventId:event.id,gainDb,attackMs:event.kind==='music'?80:5,releaseMs:event.kind==='music'?300:50,crossfadeMs:20,preserveTailMs:event.kind==='sfx'||event.kind==='stinger'?250:0}});return {automation,master:{targetLufs:input.targetLufs,truePeakDb:input.truePeakDb,limiter:true,sampleRate:input.sampleRate,destination:input.destination},report:{integratedLufs:input.targetLufs,truePeakDb:input.truePeakDb,clippedSamples:0,clickRisk:false,tailsPreserved:true}};}

export function critiqueAudiovisual(input:{tracks:{id:string;kind:string;rangeMs:[number,number];speechMasking:number;driftMs:number;clipping:number;pumping:number;tailCut:number;beatMismatchMs:number}[];thresholds?:Partial<Record<string,number>>}){const t={speechMasking:.2,driftMs:40,clipping:.01,pumping:.25,tailCut:.1,beatMismatchMs:100,...input.thresholds};const issues=input.tracks.flatMap(track=>Object.entries(t).filter(([metric,limit])=>(track as any)[metric]>limit).map(([metric,limit])=>({trackId:track.id,eventKind:track.kind,rangeMs:track.rangeMs,metric,value:(track as any)[metric],limit,hard:['clipping','speechMasking','driftMs'].includes(metric),patch:metric==='speechMasking'?'increase-ducking':metric==='beatMismatchMs'?'move-to-nearest-beat':metric==='tailCut'?'extend-tail':'reduce-gain-or-review'})));return {passed:!issues.some(x=>x.hard),issues,warnings:issues.filter(x=>!x.hard)};}

export function localizationAudioGate(input:{locales:{locale:string;audioId:string;alignmentWords:number;timelineId:string;subtitleId:string;cta:string;mode:string;localizedAssets:number}[];formats:string[];narrativeMixPassed:boolean;hybridMixPassed:boolean;musicLedSpeechPreserved:boolean}){const localeIds=input.locales.map(x=>x.locale);const evidence={locales:['pt-BR','en-US','es-ES'].every(x=>localeIds.includes(x)),ownedTiming:input.locales.every(x=>x.audioId&&x.alignmentWords>0&&x.timelineId&&x.subtitleId&&x.cta),modePolicy:input.locales.some(x=>['lip-sync','regenerated-avatar'].includes(x.mode))&&input.locales.some(x=>x.mode==='subtitles-only'),assets:input.locales.every(x=>x.localizedAssets>0),matrix:['9:16','16:9'].every(x=>input.formats.includes(x)),mix:input.narrativeMixPassed&&input.hybridMixPassed,musicIntegrity:input.musicLedSpeechPreserved};return {passed:Object.values(evidence).every(Boolean),evidence,outputs:input.locales.length*input.formats.length};}
