import { createHash } from 'node:crypto';
import type { CaptureSession, ClockPiece, Range, SyncSignal } from './capture-synchronization';

export const CAPTURE_PROTOCOLS = {
  'teacher-screen': { label: 'Professor + tela', required: ['scratch-audio-or-marker'], recommended: ['clap', 'continuous-screen-clock', 'reference-recording'], explanation: 'A tela precisa compartilhar som, marker ou um anchor manual com a câmera.' },
  podcast: { label: 'Podcast', required: ['shared-audio-event'], recommended: ['clap', 'scratch-audio', 'continuous-recording'], explanation: 'Cada câmera deve registrar o mesmo clap ou áudio de referência.' },
  react: { label: 'React', required: ['reference-media'], recommended: ['visible-player', 'scratch-audio', 'screen-recording'], explanation: 'Inclua o vídeo original e preserve eventos de play, pause e seek.' },
  multicamera: { label: 'Multicâmera', required: ['shared-marker-or-timecode'], recommended: ['clap', 'scratch-audio', 'continuous-clock'], explanation: 'Sem timecode ou evento comum, será necessário marcar o mesmo instante em cada câmera.' },
} as const;
export type CaptureScenario = keyof typeof CAPTURE_PROTOCOLS;
export function evaluateCaptureProtocol(scenario: CaptureScenario, provided: string[]) { const protocol = CAPTURE_PROTOCOLS[scenario]; const missing = protocol.required.filter(item => !provided.includes(item)); return { scenario, protocol, accepted: missing.length === 0, missing, warning: missing.length ? 'A sincronização automática ficará limitada; adicione um anchor manual.' : undefined }; }

export function createSyncMarker(id: string, sessionMs: number) { const payload = `${id}:${sessionMs}`; return { id, sessionMs, payload, flash: [255, 255, 255], chirpHz: [1800, 2400], checksum: createHash('sha256').update(payload).digest('hex').slice(0, 8) }; }
export function fuseMarkerDetections(marker: ReturnType<typeof createSyncMarker>, audio: { sessionMs: number; payload: string; confidence: number }[], video: { sessionMs: number; payload: string; confidence: number }[]) { const matches = audio.flatMap(a => video.filter(v => v.payload === marker.payload && a.payload === marker.payload && Math.abs(a.sessionMs - v.sessionMs) <= 40).map(v => ({ sessionMs: (a.sessionMs + v.sessionMs) / 2, precisionMs: Math.abs(a.sessionMs - v.sessionMs), confidence: (a.confidence + v.confidence) / 2 }))); const best = matches.sort((a, b) => b.confidence - a.confidence)[0]; return best && best.confidence >= .8 ? { detected: true, ...best } : { detected: false, reason: 'marker-not-confirmed-by-independent-signals' }; }

export type SyncDiagnostic = { method?: SyncSignal['method']; confidence: number; residualMs: number; driftPpm: number; coverage: number; warnings: string[]; actions: string[]; anchors: { sourceMs: number; sessionMs: number }[]; maps: ClockPiece[] };
export function updateManualAnchor(diagnostic: SyncDiagnostic, action: { type: 'add' | 'move' | 'remove'; index?: number; anchor?: { sourceMs: number; sessionMs: number } }) { const anchors = [...diagnostic.anchors]; if (action.type === 'add' && action.anchor) anchors.push(action.anchor); if (action.type === 'move' && action.anchor && action.index !== undefined) anchors[action.index] = action.anchor; if (action.type === 'remove' && action.index !== undefined) anchors.splice(action.index, 1); const confidence = Math.min(.99, anchors.length * .25); return { ...diagnostic, anchors, confidence, actions: confidence >= .75 ? diagnostic.actions.filter(item => item !== 'add-manual-anchor') : [...new Set([...diagnostic.actions, 'add-manual-anchor'])] }; }
export function canAutoEdit(diagnostic: SyncDiagnostic) { return diagnostic.confidence >= .82 && diagnostic.coverage >= .9 && diagnostic.residualMs <= 40 && !diagnostic.warnings.includes('insufficient-evidence'); }

export type AngleCandidate = { trackId: string; rangeMs: Range; coverage: boolean; quality: number; context: 'speaker' | 'reaction' | 'screen' | 'wide'; activeSpeaker?: boolean; protected?: boolean };
export function directMulticam(candidates: AngleCandidate[], moments: { rangeMs: Range; kind: 'speech' | 'demonstration' | 'reaction' }[], minShotMs = 1200) { let previous: string | undefined; return moments.map(moment => { const eligible = candidates.filter(item => item.coverage && item.rangeMs[0] <= moment.rangeMs[0] && item.rangeMs[1] >= moment.rangeMs[1]); const scored = eligible.map(item => ({ item, score: item.quality + (moment.kind === 'demonstration' && item.context === 'screen' ? 1 : 0) + (moment.kind === 'speech' && item.activeSpeaker ? .7 : 0) + (moment.kind === 'reaction' && item.context === 'reaction' ? .7 : 0) + (item.protected ? 2 : 0) - (item.trackId === previous ? .15 : 0) })).sort((a, b) => b.score - a.score); const selected = scored[0]?.item; if (selected) previous = selected.trackId; return { ...moment, trackId: selected?.trackId, durationMs: Math.max(minShotMs, moment.rangeMs[1] - moment.rangeMs[0]), reason: selected?.protected ? 'protected-selection' : moment.kind }; }); }

export type CameraColorSample = { cameraId: string; whiteBalanceK: number; exposureEv: number; skinHue: number; comparable: boolean };
export function matchMulticamColor(samples: CameraColorSample[], referenceCameraId: string, overrides: { cameraId: string; rangeMs: Range; exposureEv?: number }[] = []) { const reference = samples.find(item => item.cameraId === referenceCameraId); if (!reference) throw new Error('reference-camera-not-found'); return samples.map(sample => sample.cameraId === referenceCameraId ? { cameraId: sample.cameraId, match: { whiteBalanceDelta: 0, exposureDelta: 0 }, confidence: 1, stage: 'before-creative-lut' } : sample.comparable && reference.comparable ? { cameraId: sample.cameraId, match: { whiteBalanceDelta: reference.whiteBalanceK - sample.whiteBalanceK, exposureDelta: reference.exposureEv - sample.exposureEv }, overrides: overrides.filter(item => item.cameraId === sample.cameraId), confidence: .9, stage: 'before-creative-lut' } : { cameraId: sample.cameraId, issue: 'sources-not-comparable', confidence: .2, stage: 'before-creative-lut' }); }

export function critiqueColor(input: { beforeOutput: { clipping: number; cast: number; skinDeviation: number; mismatch: number }; afterOutput: { clipping: number; cast: number; skinDeviation: number; mismatch: number }; creativeIntent: { castAllowed: number }; confidence: number }) { const issues = [{ code: 'clipping', value: input.afterOutput.clipping, limit: .02 }, { code: 'cast', value: Math.max(0, input.afterOutput.cast - input.creativeIntent.castAllowed), limit: .15 }, { code: 'skin-tone', value: input.afterOutput.skinDeviation, limit: .2 }, { code: 'camera-mismatch', value: input.afterOutput.mismatch, limit: .15 }].filter(item => item.value > item.limit); return { passed: issues.length === 0, issues, beforeOutput: input.beforeOutput, action: issues.length === 0 ? 'none' : input.confidence >= .8 ? 'limited-correction' : 'human-review' }; }

export function attachProtocol(session: CaptureSession, scenario: CaptureScenario) { return { ...session, protocol: scenario }; }
