import { DomainError } from './errors.ts'

export interface DirectorBudgetLimits { cost: number; timeMs: number; tokens: number; generations: number; candidates: number; criticRounds: number }
export interface DirectorBudgetUsage extends DirectorBudgetLimits {}
export interface DirectorBudgetState { runId: string; revision: number; status: 'active' | 'budget_exhausted' | 'cancelled' | 'completed'; limits: DirectorBudgetLimits; reserved: DirectorBudgetUsage; actual: DirectorBudgetUsage }
export type BudgetDimension = keyof DirectorBudgetLimits
const dimensions: readonly BudgetDimension[] = ['cost', 'timeMs', 'tokens', 'generations', 'candidates', 'criticRounds']
const empty = (): DirectorBudgetUsage => ({ cost: 0, timeMs: 0, tokens: 0, generations: 0, candidates: 0, criticRounds: 0 })
export function createDirectorBudget(runId: string, limits: DirectorBudgetLimits): Readonly<DirectorBudgetState> { if (!runId || dimensions.some((key) => !Number.isFinite(limits[key]) || limits[key] < 0)) throw new DomainError('INVALID_ARGUMENT', 'Budget limits must be finite and non-negative'); return Object.freeze({ runId, revision: 0, status: 'active', limits: Object.freeze({ ...limits }), reserved: Object.freeze(empty()), actual: Object.freeze(empty()) }) }
export function reserveDirectorBudget(state: DirectorBudgetState, estimate: DirectorBudgetUsage): Readonly<DirectorBudgetState> { if (state.status !== 'active') throw new DomainError('INVALID_ARGUMENT', 'Budget is not active'); const reserved = Object.fromEntries(dimensions.map((key) => [key, state.reserved[key] + estimate[key]])) as unknown as DirectorBudgetUsage; if (dimensions.some((key) => reserved[key] > state.limits[key])) return Object.freeze({ ...state, revision: state.revision + 1, status: 'budget_exhausted' as const }); return Object.freeze({ ...state, revision: state.revision + 1, reserved: Object.freeze(reserved) }) }
export function settleDirectorBudget(state: DirectorBudgetState, estimate: DirectorBudgetUsage, actual: DirectorBudgetUsage): Readonly<DirectorBudgetState> { const reserved = Object.fromEntries(dimensions.map((key) => [key, Math.max(0, state.reserved[key] - estimate[key])])) as unknown as DirectorBudgetUsage; const total = Object.fromEntries(dimensions.map((key) => [key, state.actual[key] + actual[key]])) as unknown as DirectorBudgetUsage; return Object.freeze({ ...state, revision: state.revision + 1, status: dimensions.some((key) => total[key] > state.limits[key]) ? 'budget_exhausted' as const : state.status, reserved: Object.freeze(reserved), actual: Object.freeze(total) }) }
export function cancelDirectorBudget(state: DirectorBudgetState): Readonly<DirectorBudgetState> { return Object.freeze({ ...state, revision: state.revision + 1, status: 'cancelled' as const, reserved: Object.freeze(empty()) }) }
export function concludeDirectorRun<T extends { valid: boolean; score: number }>(state: DirectorBudgetState, candidates: readonly T[]) { const valid = candidates.filter((item) => item.valid).toSorted((a, b) => b.score - a.score); return Object.freeze({ status: valid.length ? 'completed-with-best-valid' as const : state.status === 'budget_exhausted' ? 'budget_exhausted' as const : 'no-valid-result' as const, result: valid[0] ?? null, recoverable: !valid.length }) }
export interface BudgetRepository { read(runId: string): Promise<DirectorBudgetState>; compareAndSwap(runId: string, expectedRevision: number, next: DirectorBudgetState): Promise<boolean> }
export async function reserveAtomically(repository: BudgetRepository, runId: string, estimate: DirectorBudgetUsage, attempts = 3) { for (let attempt = 0; attempt < attempts; attempt += 1) { const current = await repository.read(runId); const next = reserveDirectorBudget(current, estimate); if (await repository.compareAndSwap(runId, current.revision, next)) return next } throw new DomainError('PERSISTENCE_CONFLICT', 'Budget reservation conflicted repeatedly') }
