export const DOMAIN_ERROR_CODES = [
  'INVALID_ARGUMENT',
  'INVALID_OUTPUT_SPEC',
  'INVALID_SCOPE',
  'INVALID_COMMAND',
  'INVALID_PROJECT_VERSION',
  'INVALID_WORKSPACE',
  'INVALID_PROJECT',
  'INVALID_SNAPSHOT',
  'INVALID_MEDIA_ARTIFACT',
  'INVALID_RENDER_INPUT',
  'MEDIA_ARTIFACT_NOT_FOUND',
  'MEDIA_ARTIFACT_MANIFEST_NOT_FOUND',
  'MEDIA_ARTIFACT_SOURCE_NOT_FOUND',
  'MATERIALIZATION_AUTHORIZATION_NOT_FOUND',
  'MATERIALIZATION_AUTHORIZATION_REJECTED',
  'MATERIALIZATION_AUTHORIZATION_EXPIRED',
  'MATERIALIZATION_REVALIDATION_FAILED',
  'RENDER_EXECUTION_FAILED',
  'RENDER_OUTPUT_INVALID',
  'RENDER_OUTPUT_CONFLICT',
  'RENDER_OUTPUT_PROMOTION_FAILED',
  'RENDER_OUTPUT_CLEANUP_FAILED',
  'INVALID_PUBLIC_OPERATION',
  'INVALID_PUBLIC_EVENT',
  'INVALID_WEBHOOK',
  'WEBHOOK_CHALLENGE_NOT_FOUND',
  'WEBHOOK_CHALLENGE_REJECTED',
  'WEBHOOK_NETWORK_REJECTED',
  'WEBHOOK_CHALLENGE_TRANSPORT_FAILED',
  'WEBHOOK_SIGNATURE_INVALID',
  'WEBHOOK_REPLAY_DETECTED',
  'PUBLIC_OPERATION_NOT_FOUND',
  'PUBLIC_OPERATION_RETRY_REJECTED',
  'WORKSPACE_NOT_FOUND',
  'IDEMPOTENCY_PAYLOAD_MISMATCH',
  'PERSISTENCE_CONFLICT',
  'PERSISTENCE_NOT_CONFIGURED',
  'INVALID_API_CLIENT',
  'API_CLIENT_NOT_FOUND',
  'API_CREDENTIAL_NOT_FOUND',
  'AUTH_INVALID',
  'AUTH_SCOPE_REQUIRED',
  'VERSION_CONFLICT',
  'DUPLICATE_CAPABILITY',
  'INVALID_CAPABILITY',
  'INVALID_PUBLIC_SCHEMA',
  'PUBLIC_SCHEMA_NOT_FOUND',
  'CAPABILITY_PARITY_MISSING',
] as const

export type DomainErrorCode = (typeof DOMAIN_ERROR_CODES)[number]

export class DomainError extends Error {
  readonly code: DomainErrorCode
  readonly details: Readonly<Record<string, unknown>>

  constructor(
    code: DomainErrorCode,
    message: string,
    details: Record<string, unknown> = {},
  ) {
    super(message)
    this.name = 'DomainError'
    this.code = code
    this.details = Object.freeze({ ...details })
  }
}
export function assertDomain(
  condition: unknown,
  code: DomainErrorCode,
  message: string,
  details: Record<string, unknown> = {},
): asserts condition {
  if (!condition) {
    throw new DomainError(code, message, details)
  }
}
