import { createHash } from 'node:crypto';

export type SourceRange={sourceIn:number;sourceOut:number;timelineIn:number;timelineOut:number;rate:number};
export type FoundationClip={id:string;sourceId:string;range:SourceRange;protected?:{reason:string;owner:string;expiresAt?:string};metadata?:Record<string,unknown>};
export type TrackKind='base-video'|'audio'|'broll'|'overlay'|'subtitle'|'color'|'annotation';
export type FoundationTrack={id:string;kind:TrackKind;order:number;exclusive:boolean;visible:boolean;muted:boolean;locked:boolean;clips:FoundationClip[]};
export type FoundationEditPlan={schemaVersion:2;id:string;tracks:FoundationTrack[];sources:{id:string;kind:string;duration:number;ready:boolean;rights:boolean}[];outputSpec:{version:number;aspectRatio:string;width:number;height:number;fps:number;codec:string;safeArea:number};policySnapshotId:string};

export function validateEditPlan(plan:FoundationEditPlan){if(plan.schemaVersion!==2||!plan.id||!plan.policySnapshotId)throw new Error('invalid-plan-envelope');const sources=new Map(plan.sources.map(x=>[x.id,x]));for(const track of plan.tracks){if(new Set(track.clips.map(x=>x.id)).size!==track.clips.length)throw new Error('duplicate-clip');const sorted=[...track.clips].sort((a,b)=>a.range.timelineIn-b.range.timelineIn);for(let i=0;i<sorted.length;i++){const clip=sorted[i],source=sources.get(clip.sourceId);if(!source)throw new Error('missing-source');const r=clip.range;if(r.sourceIn<0||r.sourceOut<=r.sourceIn||r.timelineIn<0||r.timelineOut<=r.timelineIn||r.sourceOut>source.duration||r.rate<=0)throw new Error('invalid-range');if(track.exclusive&&i&&sorted[i-1].range.timelineOut>r.timelineIn)throw new Error('exclusive-overlap')}}return plan;}
export function trimClip(clip:FoundationClip,timelineIn:number,timelineOut:number){if(timelineIn<clip.range.timelineIn||timelineOut>clip.range.timelineOut||timelineOut<=timelineIn)throw new Error('invalid-trim');const offset=(timelineIn-clip.range.timelineIn)*clip.range.rate;return {...clip,range:{...clip.range,timelineIn,timelineOut,sourceIn:clip.range.sourceIn+offset,sourceOut:clip.range.sourceIn+offset+(timelineOut-timelineIn)*clip.range.rate}};}
export function splitClip(clip:FoundationClip,at:number){return [trimClip(clip,clip.range.timelineIn,at),trimClip(clip,at,clip.range.timelineOut)].map((x,i)=>({...x,id:`${clip.id}:${i+1}`}));}
export function resolvePlanSources(plan:FoundationEditPlan){const issues=plan.sources.flatMap(x=>[...(!x.ready?[`${x.id}:not-ready`]:[]),...(!x.rights?[`${x.id}:rights`]:[])]);return {allowed:issues.length===0,issues,resolved:issues.length?[]:plan.sources.map(x=>({id:x.id,immutable:true}))};}

export type FoundationCommand={id:string;actor:string;baseVersionId:string;scope:string[];preconditions:{target:string;hash:string}[];operations:{kind:'set-metadata'|'trim'|'remove';clipId:string;value?:unknown}[];idempotencyKey:string};
export function applyFoundationCommand(plan:FoundationEditPlan,command:FoundationCommand,input:{currentVersionId:string;actorCanUnlock:boolean;seenKeys:Set<string>}){if(input.seenKeys.has(command.idempotencyKey))return {plan,replayed:true};if(command.baseVersionId!==input.currentVersionId)throw new Error('stale-base-version');const copy=structuredClone(plan);for(const operation of command.operations){const track=copy.tracks.find(x=>x.clips.some(c=>c.id===operation.clipId));const clip=track?.clips.find(c=>c.id===operation.clipId);if(!track||!clip)throw new Error('command-target-not-found');if((track.locked||clip.protected)&&!input.actorCanUnlock)throw new Error('protected-element');if(operation.kind==='set-metadata')clip.metadata={...clip.metadata,value:operation.value};if(operation.kind==='remove')track.clips=track.clips.filter(c=>c.id!==clip.id);if(operation.kind==='trim'){const [start,end]=operation.value as [number,number];Object.assign(clip,trimClip(clip,start,end))}}validateEditPlan(copy);input.seenKeys.add(command.idempotencyKey);const patchHash=createHash('sha256').update(JSON.stringify(command.operations)).digest('hex');return {plan:copy,replayed:false,transaction:{commandId:command.id,newVersionId:`${input.currentVersionId}+1`,patchHash,audit:{actor:command.actor,scope:command.scope},atomic:true}};}

export type DependencyNode={id:string;kind:'source'|'transcript'|'perception'|'story'|'edit'|'variant'|'proxy'|'final';dependsOn:string[];range?:[number,number];variantId?:string;status:'valid'|'stale'};
export function invalidateDependencies(nodes:DependencyNode[],change:{kind:'subtitle'|'crop'|'broll'|'source-transcript';targets:string[];range?:[number,number];variantId?:string}){const stale=new Set(change.targets);let changed=true;while(changed){changed=false;for(const node of nodes)if(!stale.has(node.id)&&node.dependsOn.some(id=>stale.has(id))&&(!change.variantId||!node.variantId||node.variantId===change.variantId)){stale.add(node.id);changed=true}}const updated=nodes.map(x=>stale.has(x.id)?{...x,status:'stale' as const}:x);return {nodes:updated,stale:[...stale],minimalRenders:updated.filter(x=>x.status==='stale'&&(x.kind==='proxy'||x.kind==='final')).map(x=>({nodeId:x.id,range:change.range,variantId:x.variantId}))};}

export type CanonicalPlan={id:string;storyBlocks:string[];editPlanId:string;protectedBlocks:string[]};
export type FormatVariant={id:string;canonicalId:string;format:string;crop:Record<string,unknown>;overrides:Record<string,unknown>;protected:boolean};
export function propagateCanonicalChange(canonical:CanonicalPlan,variants:FormatVariant[],change:{block:string;replacement:string}){const updated={...canonical,storyBlocks:canonical.storyBlocks.map(x=>x===change.block?change.replacement:x)};return {canonical:updated,variants:variants.map(x=>x.protected?x:{...x,canonicalId:updated.id}),untouched:variants.filter(x=>x.protected).map(x=>x.id)};}

export type FoundationVersion={id:string;projectId:string;parentId?:string;author:string;reason:string;status:'draft'|'approved'|'archived';snapshot:unknown;createdAt:string};
export function createFoundationVersion(input:Omit<FoundationVersion,'id'|'createdAt'>){const id=`version-${createHash('sha256').update(JSON.stringify(input)).digest('hex').slice(0,12)}`;return {...input,id,createdAt:new Date().toISOString(),immutable:true};}
export function forkFoundationProject(input:{sourceProjectId:string;sourceVersion:FoundationVersion;masterRefs:string[];derivativeRefs:string[];newProjectId:string}){return {project:{id:input.newProjectId,forkedFrom:input.sourceProjectId,currentVersionId:`${input.sourceVersion.id}:fork`,status:'draft'},sharedReadOnlyRefs:[...input.masterRefs,...input.derivativeRefs],copiedBytes:0,jobs:[],annotations:[],approvals:[]};}
export function assertForkIsolation(resourceProjectId:string,commandProjectId:string){if(resourceProjectId!==commandProjectId)throw new Error('fork-isolation-violation');return true;}
export function semanticVersionDiff(before:FoundationEditPlan,after:FoundationEditPlan){const beforeClips=new Map(before.tracks.flatMap(x=>x.clips).map(x=>[x.id,x]));const afterClips=new Map(after.tracks.flatMap(x=>x.clips).map(x=>[x.id,x]));return {added:[...afterClips.keys()].filter(x=>!beforeClips.has(x)),removed:[...beforeClips.keys()].filter(x=>!afterClips.has(x)),changed:[...afterClips.keys()].filter(x=>beforeClips.has(x)&&JSON.stringify(beforeClips.get(x))!==JSON.stringify(afterClips.get(x))),settings:JSON.stringify(before.outputSpec)!==JSON.stringify(after.outputSpec)};}
export function restoreVersion(target:FoundationVersion,current:FoundationVersion,author:string){return createFoundationVersion({projectId:current.projectId,parentId:current.id,author,reason:`restore:${target.id}`,status:'draft',snapshot:structuredClone(target.snapshot)});}

export type LineageEdge={artifactId:string;versionId:string;planId:string;sourceIds:string[];jobId:string;provider?:string;hashes:Record<string,string>;tools:Record<string,string>};
export function reconstructArtifact(edge:LineageEdge,available:Set<string>){const missing=[edge.planId,...edge.sourceIds,edge.jobId].filter(x=>!available.has(x));return {reconstructable:missing.length===0,missing,recipeHash:createHash('sha256').update(JSON.stringify(edge)).digest('hex'),diagnostic:{artifactId:edge.artifactId,versions:edge.tools}};}

export type GenericJob={id:string;type:string;idempotencyKey:string;state:'queued'|'running'|'waiting'|'retrying'|'cancelled'|'failed'|'dead-letter'|'completed';attempt:number;heartbeatAt?:string;nextRetryAt?:string;checkpoints:{phase:string;when:'before'|'after';receipt?:string}[];cost:number;result?:string;error?:string};
export function transitionGenericJob(job:GenericJob,event:'claim'|'wait'|'fail-retryable'|'fail-terminal'|'cancel'|'complete',now:string){const next={...job};if(event==='claim'&&['queued','retrying'].includes(job.state)){next.state='running';next.attempt++;next.heartbeatAt=now}else if(event==='wait'&&job.state==='running')next.state='waiting';else if(event==='fail-retryable'&&['running','waiting'].includes(job.state)){next.state=job.attempt>=3?'dead-letter':'retrying';next.nextRetryAt=new Date(new Date(now).getTime()+2**job.attempt*1000).toISOString()}else if(event==='fail-terminal')next.state='failed';else if(event==='cancel'&&!['completed','dead-letter'].includes(job.state))next.state='cancelled';else if(event==='complete'&&job.state==='running'&&job.checkpoints.some(x=>x.when==='after'))next.state='completed';else throw new Error('invalid-job-transition');return next;}
export function checkpointJob(job:GenericJob,phase:string,when:'before'|'after',receipt?:string){if(when==='after'&&!receipt)throw new Error('post-effect-receipt-required');return {...job,checkpoints:[...job.checkpoints,{phase,when,receipt}]};}

export function materializePortableRender(input:{assets:{id:string;location:string;checksum:string}[];fonts:{id:string;location:string}[];luts:{id:string;location:string}[];planHash:string;rendererVersion:string}){if([...input.assets,...input.fonts,...input.luts].some(x=>!x.location))throw new Error('unmaterialized-resource');return {schemaVersion:1,...input,portableIdentity:createHash('sha256').update(JSON.stringify({assets:input.assets.map(x=>({id:x.id,checksum:x.checksum})),fonts:input.fonts.map(x=>x.id),luts:input.luts.map(x=>x.id),planHash:input.planHash,rendererVersion:input.rendererVersion})).digest('hex')};}

export const FOUNDATION_STATES={project:['draft','processing','review','completed','archived'],version:['draft','approved','archived'],job:['queued','running','waiting','retrying','cancelled','failed','dead-letter','completed'],batchItem:['queued','running','review','failed','completed','cancelled'],artifact:['staged','ready','stale','failed','archived']} as const;
export function presentFoundationState(kind:keyof typeof FOUNDATION_STATES,state:string){if(!(FOUNDATION_STATES[kind] as readonly string[]).includes(state))throw new Error('invalid-visible-state');const action:Record<string,string>={queued:'cancel',running:'view-progress',waiting:'review-dependency',retrying:'cancel',failed:'retry','dead-letter':'review',stale:'rebuild',completed:'open',ready:'open',review:'review',cancelled:'retry',archived:'restore',draft:'continue',processing:'view-progress',approved:'open',staged:'wait'};return {label:state.replaceAll('-',' '),progress:['running','processing'].includes(state)?undefined:state==='completed'||state==='ready'?100:0,indeterminate:['running','processing','waiting'].includes(state),action:action[state]??'open'};}
