export type ScriptBlock={id:string;sourceLocale:string;intent:string;text:string;claims:{text:string;qualifier?:string;attribution?:string;protected:boolean}[];cta?:{action:string;destination:string};dependencies:string[];sourceRangeMs:[number,number];alignment:{word:string;startMs:number;endMs:number}[]};
export function validateLocalizedScript(source:ScriptBlock,localized:ScriptBlock){const sourceProtected=source.claims.filter(x=>x.protected);const targetProtected=localized.claims.filter(x=>x.protected);if(sourceProtected.length!==targetProtected.length||sourceProtected.some((x,i)=>x.qualifier!==targetProtected[i]?.qualifier||x.attribution!==targetProtected[i]?.attribution))throw new Error('protected-claim-changed');if(source.cta?.action!==localized.cta?.action)throw new Error('cta-intent-changed');return localized;}

export type LocalizationStatus='draft'|'translating'|'audio'|'visual'|'review'|'approved'|'failed';
export type LocalizationVariant={id:string;canonicalVersionId:string;locale:string;scriptVersion:number;audioAssets:string[];alignment:ScriptBlock['alignment'];planId?:string;formats:string[];status:LocalizationStatus;masterRefs:string[];commands:string[];jobs:string[];approval?:string};
const LOCALIZATION_TRANSITIONS:Record<LocalizationStatus,LocalizationStatus[]>={draft:['translating','failed'],translating:['audio','failed'],audio:['visual','failed'],visual:['review','failed'],review:['approved','audio','visual','failed'],approved:[],failed:['translating']};
export function createLocalizationVariant(input:{canonicalVersionId:string;locale:string;formats:string[];masterRefs:string[]}):LocalizationVariant{return {id:`${input.canonicalVersionId}:${input.locale}`,canonicalVersionId:input.canonicalVersionId,locale:input.locale,scriptVersion:1,audioAssets:[],alignment:[],formats:input.formats,status:'draft',masterRefs:input.masterRefs,commands:[],jobs:[]};}
export function transitionLocalization(variant:LocalizationVariant,next:LocalizationStatus){if(!LOCALIZATION_TRANSITIONS[variant.status].includes(next))throw new Error('invalid-localization-transition');return {...variant,status:next};}
export function rebaseLocalization(variant:LocalizationVariant,newCanonicalVersionId:string){return variant.status==='approved'?{...variant,canonicalVersionId:newCanonicalVersionId,status:'draft' as const,scriptVersion:variant.scriptVersion+1,approval:undefined}:{...variant,canonicalVersionId:newCanonicalVersionId};}

export function alignLocalizedText(text:string,durationMs:number){const words=text.trim().split(/\s+/).filter(Boolean);const unit=durationMs/Math.max(1,words.length);return words.map((word,index)=>({word,startMs:Math.round(index*unit),endMs:Math.round((index+1)*unit)}));}
export function localizedTimingPlan(input:{source:ScriptBlock;localizedText:string;localizedDurationMs:number;policy:{maxStretch:number;allowCopyAdaptation:boolean}}){const sourceDuration=input.source.sourceRangeMs[1]-input.source.sourceRangeMs[0],ratio=input.localizedDurationMs/sourceDuration;const action=ratio>1+input.policy.maxStretch||ratio<1-input.policy.maxStretch?(input.policy.allowCopyAdaptation?'adapt-copy-and-reflow':'review'):'reflow-timeline';const alignment=alignLocalizedText(input.localizedText,input.localizedDurationMs);return {ratio,deviationMs:input.localizedDurationMs-sourceDuration,action,alignment,recompile:['subtitles','clips','broll','events'],audioStretch:false};}

export type LocalizedAudioMode='authorized-tts'|'local-voice'|'uploaded'|'lip-sync'|'regenerated-avatar'|'subtitles-only';
export function chooseLocalizedAudioMode(input:{preferred:LocalizedAudioMode[];profileModes:LocalizedAudioMode[];consent:boolean;localeSupported:boolean;providerModes:LocalizedAudioMode[];disclosureRequired:boolean;originalAudioId:string}){const selected=input.preferred.find(mode=>input.profileModes.includes(mode)&&input.providerModes.includes(mode)&&input.localeSupported&&(!['lip-sync','regenerated-avatar'].includes(mode)||input.consent))??'subtitles-only';return {selected,originalAudioId:input.originalAudioId,lineage:[input.originalAudioId,selected],disclosure:input.disclosureRequired&&selected!=='subtitles-only'?'Localized synthetic voice/video':undefined};}

export type LocaleProfile={id:string;version:number;locale:string;region:string;glossary:Record<string,string>;doNotTranslate:string[];tone:string;ctaConventions:Record<string,string>;numberFormat:string;dateFormat:string;currency:string;legalText:string[];fonts:{family:string;glyphs:string[]}[];direction:'ltr'|'rtl';lineBreak:'word'|'character'};
export function resolveLocaleProfile(workspace:LocaleProfile,override?:Partial<LocaleProfile>):LocaleProfile{return {...workspace,...override,id:override?.id??workspace.id,version:override?.version??workspace.version};}
export function validateLocaleProfile(profile:LocaleProfile){const conflicts=Object.keys(profile.glossary).filter(term=>profile.doNotTranslate.includes(term));const required=profile.direction==='rtl'?['arabic']:[];const glyphs=new Set(profile.fonts.flatMap(x=>x.glyphs));const missing=required.filter(x=>!glyphs.has(x));return {valid:!conflicts.length&&!missing.length,conflicts,missingGlyphGroups:missing};}

export type OcrRegion={id:string;text:string;box:{x:number;y:number;width:number;height:number};importance:'critical'|'supporting'|'decorative';kind:'card'|'screenshot'|'logo'|'interface'|'irrelevant'};
export function planLocalizedVisualAssets(regions:OcrRegion[],input:{translate:boolean;rights:boolean;backgroundEditable:boolean}){return regions.map(region=>{const action=!input.rights?'reject':region.kind==='logo'||region.kind==='irrelevant'?'share':!input.translate?'replace':input.backgroundEditable?'localize':'regenerate';return {...region,action,derivative:action==='localize'||action==='regenerate'?`${region.id}:localized`:undefined,preserveBackground:action==='localize',lineage:true}});}

export function critiqueLocalization(input:{blocks:{id:string;fidelity:number;claimPreserved:boolean;glossary:number;pronunciation:number;lipSync:number;typography:number;subtitleTiming:number;wordIssues?:string[];frameIssues?:number[]}[];mode:LocalizedAudioMode;locale:string}){const issues=input.blocks.flatMap(block=>{const hard=!block.claimPreserved||block.fidelity<.85||block.glossary<.9;const soft=Math.min(block.pronunciation,block.lipSync,block.typography,block.subtitleTiming)<.75;return hard||soft?[{blockId:block.id,hard,words:block.wordIssues??[],frames:block.frameIssues??[],action:!block.claimPreserved||block.glossary<.9?'retranslate':block.pronunciation<.75?'tts-retry':block.subtitleTiming<.75?'timeline-reflow':'human-review'}]:[]});return {passed:!issues.some(x=>x.hard),issues,locale:input.locale,mode:input.mode};}

export type BeatAnalysis={beatsMs:number[];downbeatsMs:number[];sections:{name:string;rangeMs:[number,number];energy:number}[];confidence:number};
export function planMusicLedMontage(input:{analysis:BeatAnalysis;candidateCutsMs:number[];protectedSpeechRanges:[number,number][];snapToleranceMs:number;maxCutsPer10s:number}){if(input.analysis.confidence<.65)return {mode:'narrative-led-fallback',cutsMs:input.candidateCutsMs,reasons:['uncertain-beat']};const cuts:number[]=[];for(const candidate of input.candidateCutsMs){const beat=[...input.analysis.beatsMs].sort((a,b)=>Math.abs(a-candidate)-Math.abs(b-candidate))[0];const snapped=Math.abs(beat-candidate)<=input.snapToleranceMs?beat:candidate;const deformsSpeech=input.protectedSpeechRanges.some(([start,end])=>snapped>start&&snapped<end);if(!deformsSpeech&&cuts.filter(x=>Math.abs(x-snapped)<=5000).length<input.maxCutsPer10s)cuts.push(snapped)}return {mode:'music-led',cutsMs:cuts,reasons:[],sections:input.analysis.sections,overEdited:cuts.length>Math.ceil((input.analysis.beatsMs.at(-1)??0)/10000*input.maxCutsPer10s)};}
