import {createHash}from'crypto';import{DomainError}from'./errors.ts'
export interface TimelineClip{id:string;sourceId:string;startMs:number;endMs:number;track:number;selected:boolean;inspector:{layout?:string;text?:string;subtitle?:string;color?:string;motion?:string;audioGain?:number}}
export interface TimelineViewModel{versionId:string;revision:number;clips:readonly TimelineClip[];snapPointsMs:readonly number[]}
export type ManualGesture={kind:'select';clipId:string}|{kind:'trim';clipId:string;edge:'start'|'end';atMs:number}|{kind:'split';clipId:string;atMs:number}|{kind:'move';clipId:string;startMs:number;track:number}|{kind:'replace';clipId:string;sourceId:string}|{kind:'inspect';clipId:string;patch:TimelineClip['inspector']}
export interface ManualEditCommand{id:string;scope:{projectId:string;variantId:string;targetId:string};baseVersionId:string;expectedRevision:number;operation:ManualGesture;createdBy:string}
const snap=(value:number,points:readonly number[],threshold=120)=>{const candidates=points.filter((point)=>Math.abs(point-value)<=threshold);return candidates.length===0?value:candidates.reduce((best,point)=>Math.abs(point-value)<Math.abs(best-value)?point:best)}
export function gestureToCommand(input:{gesture:ManualGesture;model:TimelineViewModel;projectId:string;variantId:string;actor:string}):Readonly<ManualEditCommand>{return Object.freeze({id:`cmd_${createHash('sha256').update(JSON.stringify(input)).digest('hex').slice(0,12)}`,scope:Object.freeze({projectId:input.projectId,variantId:input.variantId,targetId:input.gesture.clipId}),baseVersionId:input.model.versionId,expectedRevision:input.model.revision,operation:Object.freeze(input.gesture),createdBy:input.actor})}
export function applyManualEdit(model:TimelineViewModel,command:ManualEditCommand):Readonly<TimelineViewModel>{if(command.baseVersionId!==model.versionId||command.expectedRevision!==model.revision)throw new DomainError('VERSION_CONFLICT','Manual edit base is stale');const clips:TimelineClip[]=model.clips.map((item)=>({...item,inspector:{...item.inspector}}));const index=clips.findIndex((item)=>item.id===command.operation.clipId);if(index<0)throw new DomainError('INVALID_ARGUMENT','Timeline clip not found');const clip=clips[index],operation=command.operation;if(operation.kind==='select')clips.forEach((item)=>item.selected=item.id===clip.id);if(operation.kind==='trim'){const at=snap(operation.atMs,model.snapPointsMs);if(operation.edge==='start')clip.startMs=at;else clip.endMs=at;if(clip.endMs<=clip.startMs)throw new DomainError('INVALID_ARGUMENT','Trim must keep positive duration')}if(operation.kind==='split'){const at=snap(operation.atMs,model.snapPointsMs);if(at<=clip.startMs||at>=clip.endMs)throw new DomainError('INVALID_ARGUMENT','Split must be inside clip');clips.splice(index,1,{...clip,id:`${clip.id}:a`,endMs:at},{...clip,id:`${clip.id}:b`,startMs:at})}if(operation.kind==='move'){const duration=clip.endMs-clip.startMs;clip.startMs=snap(operation.startMs,model.snapPointsMs);clip.endMs=clip.startMs+duration;clip.track=operation.track}if(operation.kind==='replace')clip.sourceId=operation.sourceId;if(operation.kind==='inspect')clip.inspector={...clip.inspector,...operation.patch};const frozenClips:readonly TimelineClip[]=clips.map((item)=>Object.freeze({...item,inspector:Object.freeze({...item.inspector})}));return Object.freeze({versionId:`${model.versionId}:next:${command.id}`,revision:model.revision+1,clips:Object.freeze(frozenClips),snapPointsMs:model.snapPointsMs})}
export function createAuditVersion(input:{current:TimelineViewModel;command:ManualEditCommand;action:'apply'|'undo'|'redo';targetVersionId?:string}){return Object.freeze({id:`version_${input.action}_${input.command.id}`,parentId:input.current.versionId,restoresVersionId:input.targetVersionId??null,commandId:input.command.id,action:input.action,auditable:true})}
export function manualGestureFromInteraction(input:{type:'keyboard'|'mouse';key?:string;clipId:string;pointerMs?:number}):ManualGesture{if(input.type==='keyboard'){if(input.key==='s')return{kind:'split',clipId:input.clipId,atMs:input.pointerMs??0};if(input.key==='Delete')return{kind:'trim',clipId:input.clipId,edge:'end',atMs:input.pointerMs??0};return{kind:'select',clipId:input.clipId}}return{kind:'move',clipId:input.clipId,startMs:input.pointerMs??0,track:0}}
export interface VersionComparison{before:{id:string;durationMs:number;mappingId?:string;score:number;issues:readonly string[]};after:{id:string;durationMs:number;mappingId?:string;score:number;issues:readonly string[]};semanticChanges:readonly{category:string;target:string;summary:string}[]}
export function compareVersions(input:VersionComparison,mode:'toggle'|'split'|'overlay'){const synchronized=Boolean(input.before.mappingId&&input.before.mappingId===input.after.mappingId);return Object.freeze({mode,synchronized,playheadMapping:synchronized?'shared':'independent',durationDeltaMs:input.after.durationMs-input.before.durationMs,scoreDelta:input.after.score-input.before.score,issuesAdded:Object.freeze(input.after.issues.filter((issue)=>!input.before.issues.includes(issue))),issuesResolved:Object.freeze(input.before.issues.filter((issue)=>!input.after.issues.includes(issue))),semanticChanges:Object.freeze([...input.semanticChanges]),actions:Object.freeze(['accept','reopen','restore'] as const),versionsPreserved:true})}
