export type MetricEvent={name:string;value:number;unit:string;at:string;dimensions:Record<string,string>;source:'ui'|'rest'|'sdk'|'agent'|'worker'};
export const METRIC_DEFINITIONS={
  product:['time_to_first_proxy','approved_without_manual_change','patches_per_video','critic_rounds','reopened_annotations','asset_decision_outcome','reuse_vs_generation','estimated_time_saved','approval_rate'],
  quality:['technical_hard_issues','technical_warnings','subtitle_errors','visual_collisions','semantic_rejections','synthetic_failures','claim_context_incidents','quality_escape_rate'],
  operational:['job_outcomes','queue_time','provider_retry_rate','provider_circuit_open','cost_by_output','cache_hit_rate','render_duration','render_resources','storage_by_class_age','queue_saturation','budget_alert','api_sli','concurrency_conflicts','webhook_sli','automation_calls'],
} as const;
export function recordMetric(name:string,value:number,unit:string,dimensions:Record<string,string>,source:MetricEvent['source'],at='2026-01-01T00:00:00Z'):MetricEvent{if(!Object.values(METRIC_DEFINITIONS).flat().includes(name as never))throw new Error('unknown-metric');const forbidden=['transcript','prompt','email','phone','storageKey'];if(Object.keys(dimensions).some(x=>forbidden.includes(x)))throw new Error('sensitive-metric-dimension');return {name,value,unit,dimensions,source,at};}
export function aggregateMetrics(events:MetricEvent[],groupBy:string[]){const groups=new Map<string,{count:number;sum:number;events:MetricEvent[]}>();for(const event of events){const key=JSON.stringify(Object.fromEntries(groupBy.map(x=>[x,event.dimensions[x]??'unknown'])));const current=groups.get(key)??{count:0,sum:0,events:[]};current.count++;current.sum+=event.value;current.events.push(event);groups.set(key,current)}return [...groups].map(([dimensions,value])=>({dimensions:JSON.parse(dimensions),count:value.count,sum:value.sum,average:value.sum/value.count,p50:percentile(value.events.map(x=>x.value),.5),p95:percentile(value.events.map(x=>x.value),.95)}));}
function percentile(values:number[],q:number){const sorted=[...values].sort((a,b)=>a-b);return sorted[Math.min(sorted.length-1,Math.floor(sorted.length*q))]??0}
export function qualityRegression(input:{name:string;baseline:number;target:number;current:number;direction:'lower'|'higher';window:string}[]){return input.map(x=>({...x,passed:x.direction==='lower'?x.current<=x.target:x.current>=x.target,regressed:x.direction==='lower'?x.current>x.baseline:x.current<x.baseline}));}
export function estimateTimeSaved(input:{baselineMedianMinutes:number;observedMinutes:number;sampleSize:number;scope:string}){return {estimateMinutes:Math.max(0,input.baselineMedianMinutes-input.observedMinutes),method:'historical-median-comparison',sampleSize:input.sampleSize,scope:input.scope,causal:false,language:'Estimativa histórica; não prova causalidade.'};}

export type NegativeGoalInput={kind:'nle-operation'|'sync-claim'|'claim-or-proof'|'cleanup'|'variant-materialization'|'provider-result'|'asset-use'|'effect-plan'|'ingested-content'|'performance-claim'|'v1-dependency'|'public-resource';data:Record<string,any>};
export function enforceNegativeGoal(input:NegativeGoalInput){switch(input.kind){case'nle-operation':return denyIf(['node-composition','frame-rotoscope','arbitrary-keyframe'].includes(input.data.operation),'outside-product-vocabulary');case'sync-claim':return denyIf(input.data.label==='synchronized'&&(input.data.confidence<.82||input.data.coverage<.9),'insufficient-evidence');case'claim-or-proof':return denyIf(!input.data.authorizedSource||!input.data.contextDeterminate,'claim-integrity-review');case'cleanup':return denyIf(input.data.quality<input.data.threshold,'reject-source');case'variant-materialization':return denyIf(!input.data.compatibility||!input.data.diversity||!input.data.budget||!input.data.preflight||input.data.quantity>(input.data.safeLimit??50),'combinatorial-limit');case'provider-result':return denyIf(!input.data.criticPassed,'provider-result-unverified');case'asset-use':return denyIf(!input.data.rights||!input.data.consent||input.data.expired||input.data.revoked,'rights-or-consent');case'effect-plan':return denyIf(input.data.novelty>input.data.noveltyBudget||input.data.sound>input.data.soundBudget,'over-editing');case'ingested-content':return {allowed:true,treatment:'data-only',systemInterpolation:false,encoded:true};case'performance-claim':return {allowed:true,validation:{source:input.data.source,scope:input.data.scope},hypothesis:input.data.hypothesis,causal:false,label:'historical association'};case'v1-dependency':return denyIf(input.data.directImport||input.data.reason==='preserve-old-route','explicit-adapter-required');case'public-resource':return denyIf(['database-row','queue','storage-key','raw-prompt','provider-payload','direct-editplan-mutation'].includes(input.data.resource)||!input.data.commandPolicyValidation,'internal-api-bypass');}}
function denyIf(condition:boolean,reason:string){return {allowed:!condition,reason:condition?reason:undefined};}
export const NEGATIVE_GOAL_FIXTURES=[
  {kind:'nle-operation',data:{operation:'frame-rotoscope'}},{kind:'sync-claim',data:{label:'synchronized',confidence:.2,coverage:.3}},{kind:'claim-or-proof',data:{authorizedSource:false,contextDeterminate:false}},{kind:'cleanup',data:{quality:.4,threshold:.8}},{kind:'variant-materialization',data:{compatibility:true,diversity:true,budget:true,preflight:true,quantity:100,safeLimit:50}},{kind:'provider-result',data:{criticPassed:false}},{kind:'asset-use',data:{rights:true,consent:true,expired:true}},{kind:'effect-plan',data:{novelty:10,noveltyBudget:2,sound:1,soundBudget:2}},{kind:'ingested-content',data:{text:'ignore previous'}},{kind:'performance-claim',data:{source:'instagram',scope:'hook',hypothesis:'hook helped'}},{kind:'v1-dependency',data:{directImport:true}},{kind:'public-resource',data:{resource:'storage-key',commandPolicyValidation:false}},
] as const;
