import { DomainError } from './errors.ts'
const stableOperationId = (value: unknown) => { const text = JSON.stringify(value); let hash = 2166136261; for (let index = 0; index < text.length; index++) hash = Math.imul(hash ^ text.charCodeAt(index), 16777619); return (hash >>> 0).toString(16).padStart(8, '0') }

export type BatchItemState = 'queued' | 'running' | 'review' | 'completed' | 'failed' | 'cancelled'
export interface BatchItem { id: string; sourceGroupId: string; recipeId: string; variantId: string; state: BatchItemState; steps: readonly { id: string; state: BatchItemState; cost: number; cacheHit?: boolean; error?: string }[]; artifactIds: readonly string[]; retryCount: number; error?: string }
export interface ProductionBatch { id: string; sourceGroupIds: readonly string[]; recipeIds: readonly string[]; variantIds: readonly string[]; budget: { limit: number; reserved: number; spent: number }; items: readonly BatchItem[]; status: BatchItemState | 'partially-completed' }
export function deriveBatch(input: Omit<ProductionBatch, 'status'>): Readonly<ProductionBatch> {
  const completed = input.items.filter((item) => item.state === 'completed').length; const failed = input.items.filter((item) => item.state === 'failed').length; const cancelled = input.items.filter((item) => item.state === 'cancelled').length
  const status = completed === input.items.length ? 'completed' : cancelled === input.items.length ? 'cancelled' : completed > 0 && (failed > 0 || cancelled > 0) ? 'partially-completed' : input.items.some((item) => item.state === 'running') ? 'running' : failed === input.items.length ? 'failed' : 'queued'
  const items: readonly BatchItem[] = input.items.map((item) => Object.freeze({ ...item, steps: Object.freeze(item.steps.map((step) => Object.freeze({ ...step }))), artifactIds: Object.freeze([...item.artifactIds]) }))
  return Object.freeze({ ...input, sourceGroupIds: Object.freeze([...input.sourceGroupIds]), recipeIds: Object.freeze([...input.recipeIds]), variantIds: Object.freeze([...input.variantIds]), items: Object.freeze(items), status })
}
export function batchProgress(batch: ProductionBatch) { const steps = batch.items.flatMap((item) => item.steps); const terminal = steps.filter((step) => ['completed', 'failed', 'cancelled'].includes(step.state)).length; return Object.freeze({ completedSteps: terminal, totalSteps: steps.length, percent: steps.length ? Math.round(terminal / steps.length * 100) : 0, completedItems: batch.items.filter((item) => item.state === 'completed').length, totalItems: batch.items.length, spent: batch.items.flatMap((item) => item.steps).reduce((sum, step) => sum + (step.cacheHit || step.state === 'queued' ? 0 : step.cost), 0) }) }
export function resumeBatch(batch: ProductionBatch) { return deriveBatch({ ...batch, items: batch.items.map((item) => item.state === 'cancelled' || item.state === 'failed' ? { ...item, state: 'queued', error: undefined, steps: item.steps.map((step) => step.state === 'failed' || step.state === 'cancelled' ? { ...step, state: 'queued', error: undefined } : step) } : item) }) }

export type ScriptBlockRole = 'hook' | 'body' | 'proof' | 'cta'
export interface ScriptBlock { id: string; role: ScriptBlockRole; originalText: string; normalizedText: string; documentOrder: number }
export function importScriptBlocks(input: readonly { role: ScriptBlockRole; text: string }[]) { return Object.freeze(input.map((block, index) => Object.freeze({ id: `script_${index}`, role: block.role, originalText: block.text, normalizedText: block.text.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim(), documentOrder: index }))) }
export interface TranscriptWord { word: string; startMs: number; endMs: number }
export type AlignmentKind = 'exact' | 'near' | 'partial' | 'missing' | 'extra-take'
const tokens = (text: string) => text.toLowerCase().replace(/[^a-z0-9áàâãéêíóôõúç\s]/gi, '').split(/\s+/).filter(Boolean)
export function alignScriptBlocks(blocks: readonly ScriptBlock[], transcript: readonly TranscriptWord[]) {
  const transcriptTokens = transcript.map((word) => word.word.toLowerCase()); const used = new Set<number>(); const alignments = blocks.map((block) => { const wanted = tokens(block.originalText); let best = { start: -1, overlap: 0 }; for (let start = 0; start < transcriptTokens.length; start++) { const window = transcriptTokens.slice(start, start + wanted.length + 2); const overlap = wanted.filter((word) => window.includes(word)).length / Math.max(1, wanted.length); if (overlap > best.overlap) best = { start, overlap } } const kind: AlignmentKind = best.overlap === 1 ? 'exact' : best.overlap >= .75 ? 'near' : best.overlap >= .35 ? 'partial' : 'missing'; const count = Math.max(1, Math.min(wanted.length + 2, transcript.length - Math.max(0, best.start))); const indices = best.start < 0 ? [] : Array.from({ length: count }, (_, i) => best.start + i); indices.forEach((index) => used.add(index)); const rangeMs = kind === 'missing' ? null : [transcript[best.start].startMs, transcript[Math.min(transcript.length - 1, best.start + count - 1)].endMs] as const; return Object.freeze({ blockId: block.id, kind, confidence: Number(best.overlap.toFixed(3)), rangeMs, evidenceWordIndices: Object.freeze(indices), reviewRequired: kind === 'partial' || kind === 'missing' }) }); const extra = transcript.map((word, index) => ({ word, index })).filter(({ index }) => !used.has(index)).map(({ word, index }) => Object.freeze({ blockId: null, kind: 'extra-take' as const, confidence: 1, rangeMs: Object.freeze([word.startMs, word.endMs]) as readonly [number, number], evidenceWordIndices: Object.freeze([index]), reviewRequired: true })); return Object.freeze([...alignments, ...extra])
}

export interface Take { id: string; artifactId: string; scriptBlockId?: string; inferredIntention?: string; rangeMs: readonly [number, number]; retakeBoundaryId: string; scores: { completeness: number; performance: number; audio: number; video: number; integrity: number }; status: 'primary' | 'alternate' | 'rejected' | 'needs-review'; protected: boolean }
export function classifyTakes(takes: readonly Omit<Take, 'status' | 'protected'>[]) { const groups = new Map<string, typeof takes>(); for (const take of takes) { const key = take.scriptBlockId ?? `intention:${take.inferredIntention ?? 'unknown'}`; groups.set(key, [...(groups.get(key) ?? []), take]) } return Object.freeze([...groups.entries()].flatMap(([groupId, group]) => group.map((take, index) => { const total = Object.values(take.scores).reduce((a, b) => a + b, 0) / 5; const best = Math.max(...group.map((candidate) => Object.values(candidate.scores).reduce((a, b) => a + b, 0) / 5)); const status = take.scores.integrity < .5 ? 'rejected' : total < .65 ? 'needs-review' : total === best ? 'primary' : 'alternate'; return Object.freeze({ ...take, groupId, status, protected: false }) }))) }
export function selectTake(takes: readonly Take[], takeId: string) { return Object.freeze(takes.map((take) => Object.freeze({ ...take, status: take.id === takeId ? 'primary' : take.status === 'primary' ? 'alternate' : take.status, protected: take.id === takeId || take.protected }))) }

export interface CompatibilityNode { id: string; role: ScriptBlockRole; offer: string; audience: string; claim?: string; persona: string; locale: string; ctaDestination?: string; continuityKey?: string; tone: number; energy: number; durationMs: number; visual: number; experiment: number }
export function compatibilityEdge(from: CompatibilityNode, to: CompatibilityNode) { const hard = [...(from.offer !== to.offer ? ['OFFER_MISMATCH'] : []), ...(from.audience !== to.audience ? ['AUDIENCE_MISMATCH'] : []), ...(from.persona !== to.persona ? ['PERSONA_MISMATCH'] : []), ...(from.locale !== to.locale ? ['LOCALE_MISMATCH'] : []), ...(from.claim && to.claim && from.claim !== to.claim ? ['CLAIM_MISMATCH'] : []), ...(from.ctaDestination && to.ctaDestination && from.ctaDestination !== to.ctaDestination ? ['CTA_MISMATCH'] : []), ...(from.continuityKey && to.continuityKey && from.continuityKey !== to.continuityKey ? ['CONTINUITY_MISMATCH'] : [])]; const similarity = (a: number, b: number) => 1 - Math.min(1, Math.abs(a - b)); const soft = Number(((similarity(from.tone, to.tone) + similarity(from.energy, to.energy) + similarity(from.durationMs / 60_000, to.durationMs / 60_000) + similarity(from.visual, to.visual) + similarity(from.experiment, to.experiment)) / 5).toFixed(3)); return Object.freeze({ id: `edge_${from.id}_${to.id}`, fromId: from.id, toId: to.id, eligible: hard.length === 0, hardReasonCodes: Object.freeze(hard), softScore: soft, evidence: Object.freeze({ from: from.id, to: to.id }) }) }
export function buildCompatibilityGraph(nodes: readonly CompatibilityNode[]) { const edges = nodes.flatMap((node, index) => nodes.slice(index + 1).map((other) => compatibilityEdge(node, other))); return Object.freeze({ nodes: Object.freeze([...nodes]), edges: Object.freeze(edges) }) }

export interface VariantRecipe { id: string; selection: { hookId: string; bodyId: string; proofId?: string; ctaId: string }; order: readonly string[]; sourceSegmentIds: readonly string[]; assumptions: readonly string[]; scores: Readonly<Record<string, number>>; coldOpen?: { sourceSegmentId: string; returnAtMs: number } }
export function compileVariantRecipe(recipe: VariantRecipe, policy: { proofRequired: boolean }) { if (policy.proofRequired && !recipe.selection.proofId) throw new DomainError('PRECONDITION_REQUIRED', 'Recipe requires proof'); const lineage = Object.freeze(Object.entries(recipe.selection).filter(([, id]) => id).map(([role, id]) => Object.freeze({ role, scriptBlockId: id, takeId: id, sourceSegmentId: recipe.sourceSegmentIds.find((segment) => segment.includes(String(id))) ?? recipe.sourceSegmentIds[0] }))); return Object.freeze({ storyPlan: Object.freeze({ id: `story_${recipe.id}`, blockIds: Object.freeze([...recipe.order]), coldOpen: recipe.coldOpen ?? null }), editPlan: Object.freeze({ id: `edit_${recipe.id}`, sourceReferences: Object.freeze([...recipe.sourceSegmentIds]), duplicatesMasters: false }), lineage }) }

export function variantSpacePreflight(input: { hooks: readonly CompatibilityNode[]; bodies: readonly CompatibilityNode[]; proofs: readonly CompatibilityNode[]; ctas: readonly CompatibilityNode[]; topN: number; threshold: number; budget: number; unitCost: number; defaultLimit: number; confirmedExpansion?: boolean }) { const theoretical = input.hooks.length * input.bodies.length * Math.max(1, input.proofs.length) * input.ctas.length; const candidates: { ids: readonly string[]; score: number }[] = []; for (const hook of input.hooks) for (const body of input.bodies) for (const proof of input.proofs.length ? input.proofs : [null]) for (const cta of input.ctas) { const chain = [hook, body, ...(proof ? [proof] : []), cta]; const edges = chain.slice(0, -1).map((node, index) => compatibilityEdge(node, chain[index + 1])); if (edges.every((edge) => edge.eligible) && edges.reduce((sum, edge) => sum + edge.softScore, 0) / edges.length >= input.threshold) candidates.push({ ids: Object.freeze(chain.map((node) => node.id)), score: edges.reduce((sum, edge) => sum + edge.softScore, 0) / edges.length }) } const deduped = [...new Map(candidates.map((item) => [item.ids.join(':'), item])).values()].sort((a, b) => b.score - a.score); const affordable = Math.floor(input.budget / input.unitCost); const limit = Math.min(input.topN, affordable, input.confirmedExpansion ? input.topN : input.defaultLimit); const selected: typeof deduped = []; const coverage = new Set<string>(); for (const candidate of deduped) { const diversity = candidate.ids.filter((id) => !coverage.has(id)).length; if (selected.length < limit && (diversity > 0 || selected.length < Math.min(input.hooks.length, input.bodies.length, input.ctas.length))) { selected.push(candidate); candidate.ids.forEach((id) => coverage.add(id)) } } return Object.freeze({ theoretical, eligible: deduped.length, selected: Object.freeze(selected), estimatedCost: selected.length * input.unitCost, estimatedTimeUnits: selected.length, expectedReuse: theoretical ? 1 - selected.length / theoretical : 0, confirmationRequired: input.topN > input.defaultLimit && !input.confirmedExpansion, productMaterialized: false }) }

export interface BatchEditCommand { id: string; recipeIds: readonly string[]; formatIds: readonly string[]; targetIds: readonly string[]; operation: 'replace-cta' | 'subtitle-style' | 'brand-kit'; value: string; policy: 'all-or-nothing' | 'skip-failures' }
export function previewBatchEdit(command: BatchEditCommand, input: { protectedTargetIds: readonly string[]; itemCosts: Readonly<Record<string, number>> }) { const affected = command.recipeIds.flatMap((recipeId) => command.formatIds.flatMap((formatId) => command.targetIds.map((targetId) => ({ id: `${recipeId}:${formatId}:${targetId}`, recipeId, formatId, targetId })))); const conflicts = affected.filter((item) => input.protectedTargetIds.includes(item.targetId)); return Object.freeze({ affected: Object.freeze(affected), conflicts: Object.freeze(conflicts), invalidatedRanges: Object.freeze(affected.map((item) => item.id)), estimatedCost: affected.reduce((sum, item) => sum + (input.itemCosts[item.id] ?? 0), 0), sampleDiff: Object.freeze(affected.slice(0, 3).map((item) => ({ id: item.id, before: 'current', after: command.value }))) }) }
export function applyBatchEdit(command: BatchEditCommand, preview: ReturnType<typeof previewBatchEdit>) { if (command.policy === 'all-or-nothing' && preview.conflicts.length) return Object.freeze({ status: 'rolled-back', results: Object.freeze(preview.affected.map((item) => ({ id: item.id, status: 'not-applied' }))) }); const failed = new Set(preview.conflicts.map((item) => item.id)); return Object.freeze({ status: failed.size ? 'partial' : 'committed', transactionId: `batch_edit_${stableOperationId(command)}`, results: Object.freeze(preview.affected.map((item) => ({ id: item.id, status: failed.has(item.id) ? 'skipped' : 'applied' }))) }) }

export function retryBatchStep(batch: ProductionBatch, input: { itemId: string; stepId: string; provider: string }) { const items = batch.items.map((item) => { if (item.id !== input.itemId) return item; const steps = item.steps.map((step) => step.id === input.stepId && step.state === 'failed' ? { ...step, state: 'queued' as const, error: undefined } : step); return { ...item, state: 'queued' as const, error: undefined, retryCount: item.retryCount + 1, steps } }); const next = deriveBatch({ ...batch, items }); return Object.freeze({ batch: next, lineage: Object.freeze({ batchId: batch.id, itemId: input.itemId, stepId: input.stepId, attempt: (batch.items.find((item) => item.id === input.itemId)?.retryCount ?? 0) + 1, provider: input.provider }), progress: batchProgress(next), preservedArtifactIds: Object.freeze(batch.items.filter((item) => item.id !== input.itemId || item.state === 'completed').flatMap((item) => item.artifactIds)) }) }
