import { DomainError } from './errors.ts'
export type ContaminationKind='burned-caption'|'logo-watermark'|'music'|'border'|'overlay'
export interface Contamination{id:string;kind:ContaminationKind;rangeMs:readonly[number,number];region:{x:number;y:number;width:number;height:number};confidence:number;overlapsEssential:boolean}
export interface DeconstructionInput{artifactId:string;durationMs:number;semanticRanges:readonly{role:'hook'|'body'|'cta'|'tail';rangeMs:readonly[number,number];essential:boolean}[];contaminations:readonly Contamination[]}
export function deconstructSource(input:DeconstructionInput){if(input.durationMs<=0)throw new DomainError('INVALID_ARGUMENT','Source duration is invalid');const essential=input.semanticRanges.filter(x=>x.essential&&x.role!=='tail');const cleanCandidateRanges=essential.map(x=>x.rangeMs);const confidence=essential.length?essential.reduce((s,x)=>s+(x.rangeMs[1]>x.rangeMs[0]?1:0),0)/essential.length:0;const contaminants=input.contaminations.map(item=>Object.freeze({...item,removableWithoutDamage:!item.overlapsEssential}));return Object.freeze({schemaVersion:'deconstruction-report/v1',artifactId:input.artifactId,hookEnvelope:essential.find(x=>x.role==='hook')?.rangeMs??null,bodyRanges:Object.freeze(essential.filter(x=>x.role==='body').map(x=>x.rangeMs)),ctaRanges:Object.freeze(essential.filter(x=>x.role==='cta').map(x=>x.rangeMs)),cleanCandidateRanges:Object.freeze(cleanCandidateRanges),contaminants:Object.freeze(contaminants),confidence,comparison:Object.freeze({sourceRangeMs:[0,input.durationMs]as const,cleanRangesMs:Object.freeze(cleanCandidateRanges)}),contextPreserved:cleanCandidateRanges.every(([start,end])=>start>=0&&end<=input.durationMs)})}
export function diagnoseContamination(items:readonly Contamination[]){return Object.freeze({director:Object.freeze(items.map(x=>({code:x.kind,rangeMs:x.rangeMs,region:x.region,confidence:x.confidence,blocked:x.overlapsEssential}))),humanReviewRequired:items.some(x=>x.overlapsEssential||x.confidence<.75),overlaps:Object.freeze(items.flatMap((a,i)=>items.slice(i+1).filter(b=>a.rangeMs[0]<b.rangeMs[1]&&b.rangeMs[0]<a.rangeMs[1]).map(b=>[a.id,b.id]as const)))})}
export type CleanupStrategy='trim'|'crop-reframe'|'cover'|'reject'
export function planCleanup(input:{sourceArtifactId:string;contamination:Contamination;residualQuality:number;integrity:number;costs:Readonly<Record<Exclude<CleanupStrategy,'reject'>,number>>;maxCost:number}){const c=input.contamination;const viable:{strategy:CleanupStrategy;score:number;reason:string}[]=[];if(c.rangeMs[0]===0||c.rangeMs[1]>0)viable.push({strategy:'trim',score:input.integrity-(c.overlapsEssential?.8:0),reason:'remove-time-range'});if(c.region.width<.25||c.region.height<.2)viable.push({strategy:'crop-reframe',score:input.residualQuality-(input.costs['crop-reframe']>input.maxCost?.5:0),reason:'remove-edge-region'});viable.push({strategy:'cover',score:input.residualQuality-(c.overlapsEssential?.7:0)-(input.costs.cover>input.maxCost?.5:0),reason:'replace-region'});const best=viable.sort((a,b)=>b.score-a.score)[0];const selected:CleanupStrategy=!best||best.score<.55?'reject':best.strategy;return Object.freeze({selected,candidates:Object.freeze(viable),derivative:selected==='reject'?null:Object.freeze({id:`derived_${input.sourceArtifactId}_${c.id}`,sourceArtifactId:input.sourceArtifactId,sourceImmutable:true,strategy:selected}),postCleanupReview:Object.freeze({rightsReevaluationRequired:selected!=='reject',visualReevaluationRequired:selected!=='reject'}),rejected:selected==='reject'})}
export interface ValidationEnvelope{segmentId:string;protected:readonly('copy'|'take'|'framing'|'timing'|'opening')[];scope:'hook'|'whole-video'}
export function applyValidationEnvelope(envelope:ValidationEnvelope,input:{changes:readonly('copy'|'take'|'framing'|'timing'|'opening')[];composition:{hookId:string;bodyId:string;ctaId:string}}){const violations=input.changes.filter(x=>envelope.protected.includes(x));return Object.freeze({allowed:violations.length===0,approvalRequired:violations.length>0,violations:Object.freeze(violations),decisionLog:Object.freeze({segmentId:envelope.segmentId,validation:violations.length?'lost':'preserved',newBodyId:input.composition.bodyId,newCtaId:input.composition.ctaId,excessMaterialIncluded:false})})}
export const DECONSTRUCTION_GOLDENS=Object.freeze(['burned-caption','logo-watermark','music','border','overlay'].map((kind,index)=>Object.freeze({id:`golden-${kind}`,contamination:{id:`c${index}`,kind,rangeMs:[index*1000,index*1000+800],region:{x:index%2?0:.1,y:.8,width:.2,height:.1},confidence:.95,overlapsEssential:index===4}})))
