import { createHash } from 'node:crypto'

import { calculateCanonicalHash } from './canonical-hash.ts'
import { assertDomain } from './errors.ts'

export const SYNTHETIC_MASTER_ASSET_SCHEMA_VERSION = 'synthetic-master-asset/v1' as const

const ID = /^[A-Za-z0-9][A-Za-z0-9._:/-]{2,127}$/
const HASH = /^[a-f0-9]{64}$/
const LOCALE = /^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$/
const CURRENCY = /^[A-Z]{3}$/

/**
 * The four ingested roles a master always owns. `provider-original` is the
 * provider output as delivered, `normalized-video` the deterministic
 * normalization, `final-audio` the separated audio that governs the timeline
 * and `alignment` the persisted word timing. Captions, LUTs, B-roll and
 * composition are derived downstream and deliberately absent: spec 06 §13
 * keeps them out of the master so a new edit never rewrites generated bytes.
 */
export const SYNTHETIC_MASTER_ARTIFACT_ROLES = Object.freeze([
  'provider-original',
  'normalized-video',
  'final-audio',
  'alignment',
] as const)
export type SyntheticMasterArtifactRole = (typeof SYNTHETIC_MASTER_ARTIFACT_ROLES)[number]

const ROLE_MEDIA_TYPE: Readonly<Record<SyntheticMasterArtifactRole, readonly string[]>> = Object.freeze({
  'provider-original': Object.freeze(['video', 'audio']),
  'normalized-video': Object.freeze(['video']),
  'final-audio': Object.freeze(['audio']),
  alignment: Object.freeze(['data']),
})

export interface SyntheticMasterArtifactRef {
  role: SyntheticMasterArtifactRole
  artifactId: string
  /** Content address of the bytes actually ingested into storage. */
  sha256: string
  byteSize: number
  mediaType: string
  container: string
}

/**
 * Sanitized provider provenance. The adapter config is represented only by its
 * canonical hash: raw provider payloads carry secrets and signed URLs and must
 * never reach a durable master row.
 */
export interface SyntheticMasterProvenance {
  adapterId: string
  adapterVersion: string
  capability: string
  modelRef: string | null
  adapterConfigHash: string
  providerJobId: string
  providerJobRef: string
}

export interface SyntheticMasterCost {
  currency: string
  minorUnits: number
  latencyMs: number
}

export interface SyntheticMasterCriticRef {
  reportId: string
  reportHash: string
  decision: 'approved'
}

export interface SyntheticMasterAsset {
  schemaVersion: typeof SYNTHETIC_MASTER_ASSET_SCHEMA_VERSION
  id: string
  workspaceId: string
  projectId: string
  projectVersionId: string
  /** Logical presenter plus the exact snapshot the bytes were generated from. */
  profileId: string
  profileSnapshotId: string
  profileVersion: number
  consentSnapshotHash: string
  authorizationHash: string
  rightsSnapshotId: string | null
  artifacts: readonly Readonly<SyntheticMasterArtifactRef>[]
  scriptText: string
  scriptHash: string
  alignmentHash: string
  locale: string
  /** Audio governs the master timeline; video must agree within tolerance. */
  durationMs: number
  audioDurationMs: number
  videoDurationMs: number
  provenance: Readonly<SyntheticMasterProvenance>
  cost: Readonly<SyntheticMasterCost>
  critic: Readonly<SyntheticMasterCriticRef>
  /** Block generations whose approved bytes composed this master, in order. */
  lineage: readonly string[]
  createdAt: string
  masterHash: string
}

/**
 * Audio is the master timeline (spec 06 invariant 2). A video track that drifts
 * further than one 30fps frame from the audio is not the same performance, so
 * the master refuses to exist instead of publishing an incoherent duration.
 */
export const SYNTHETIC_MASTER_DURATION_TOLERANCE_MS = 34

function instant(value: string, field: string): string {
  assertDomain(
    Number.isFinite(Date.parse(value)) && new Date(value).toISOString() === value,
    'INVALID_ARGUMENT',
    `${field} must be a canonical ISO instant`,
  )
  return value
}

function positiveDuration(value: number, field: string): number {
  assertDomain(Number.isSafeInteger(value) && value > 0, 'INVALID_ARGUMENT', `${field} must be a positive integer`)
  return value
}

function assertArtifacts(artifacts: readonly Readonly<SyntheticMasterArtifactRef>[]): readonly Readonly<SyntheticMasterArtifactRef>[] {
  const byRole = new Map<SyntheticMasterArtifactRole, Readonly<SyntheticMasterArtifactRef>>()
  for (const artifact of artifacts) {
    assertDomain(
      SYNTHETIC_MASTER_ARTIFACT_ROLES.includes(artifact.role),
      'INVALID_ARGUMENT',
      `master artifact role ${artifact.role} is not part of the master`,
    )
    assertDomain(!byRole.has(artifact.role), 'INVALID_ARGUMENT', `master artifact role ${artifact.role} is duplicated`)
    assertDomain(ID.test(artifact.artifactId), 'INVALID_ARGUMENT', 'master artifact id is invalid')
    assertDomain(HASH.test(artifact.sha256), 'INVALID_ARGUMENT', 'master artifact sha256 is invalid')
    assertDomain(
      Number.isSafeInteger(artifact.byteSize) && artifact.byteSize > 0,
      'INVALID_ARGUMENT',
      'master artifact byteSize is invalid',
    )
    assertDomain(
      ROLE_MEDIA_TYPE[artifact.role].includes(artifact.mediaType),
      'INVALID_ARGUMENT',
      `master artifact role ${artifact.role} cannot carry media type ${artifact.mediaType}`,
    )
    assertDomain(artifact.container.trim().length > 0, 'INVALID_ARGUMENT', 'master artifact container is required')
    byRole.set(artifact.role, Object.freeze({ ...artifact }))
  }
  for (const role of SYNTHETIC_MASTER_ARTIFACT_ROLES) {
    assertDomain(byRole.has(role), 'INVALID_ARGUMENT', `master is missing its ${role} artifact`)
  }
  // Canonical order keeps the master hash independent of insertion order.
  return Object.freeze(SYNTHETIC_MASTER_ARTIFACT_ROLES.map((role) => byRole.get(role)!))
}

/**
 * Integral content address of the master. Everything that identifies the
 * generated performance participates; nothing observational does, so re-reading
 * a master from PostgreSQL and re-hashing it must reproduce the stored value.
 */
export function calculateSyntheticMasterHash(
  master: Omit<SyntheticMasterAsset, 'masterHash'>,
): string {
  return calculateCanonicalHash({
    schemaVersion: master.schemaVersion,
    id: master.id,
    workspaceId: master.workspaceId,
    projectId: master.projectId,
    projectVersionId: master.projectVersionId,
    profileId: master.profileId,
    profileSnapshotId: master.profileSnapshotId,
    profileVersion: master.profileVersion,
    consentSnapshotHash: master.consentSnapshotHash,
    authorizationHash: master.authorizationHash,
    rightsSnapshotId: master.rightsSnapshotId,
    artifacts: master.artifacts.map((artifact) => ({
      role: artifact.role,
      artifactId: artifact.artifactId,
      sha256: artifact.sha256,
      byteSize: artifact.byteSize,
      mediaType: artifact.mediaType,
      container: artifact.container,
    })),
    scriptHash: master.scriptHash,
    alignmentHash: master.alignmentHash,
    locale: master.locale,
    durationMs: master.durationMs,
    audioDurationMs: master.audioDurationMs,
    videoDurationMs: master.videoDurationMs,
    provenance: {
      adapterId: master.provenance.adapterId,
      adapterVersion: master.provenance.adapterVersion,
      capability: master.provenance.capability,
      modelRef: master.provenance.modelRef,
      adapterConfigHash: master.provenance.adapterConfigHash,
      providerJobId: master.provenance.providerJobId,
      providerJobRef: master.provenance.providerJobRef,
    },
    cost: { currency: master.cost.currency, minorUnits: master.cost.minorUnits, latencyMs: master.cost.latencyMs },
    critic: { reportId: master.critic.reportId, reportHash: master.critic.reportHash, decision: master.critic.decision },
    lineage: [...master.lineage],
    createdAt: master.createdAt,
  })
}

export function createSyntheticMasterAsset(
  input: Omit<SyntheticMasterAsset, 'schemaVersion' | 'scriptHash' | 'masterHash'> & { scriptHash?: string },
): Readonly<SyntheticMasterAsset> {
  for (const [field, value] of Object.entries({
    id: input.id,
    workspaceId: input.workspaceId,
    projectId: input.projectId,
    projectVersionId: input.projectVersionId,
    profileId: input.profileId,
    profileSnapshotId: input.profileSnapshotId,
  })) {
    assertDomain(ID.test(value), 'INVALID_ARGUMENT', `master.${field} is invalid`)
  }
  assertDomain(
    Number.isSafeInteger(input.profileVersion) && input.profileVersion >= 1,
    'INVALID_ARGUMENT',
    'master.profileVersion is invalid',
  )
  assertDomain(
    HASH.test(input.consentSnapshotHash) && HASH.test(input.authorizationHash) && HASH.test(input.alignmentHash),
    'INVALID_ARGUMENT',
    'master consent, authorization and alignment hashes are required',
  )
  assertDomain(
    input.rightsSnapshotId === null || ID.test(input.rightsSnapshotId),
    'INVALID_ARGUMENT',
    'master.rightsSnapshotId is invalid',
  )
  const scriptText = input.scriptText.trim()
  assertDomain(scriptText.length > 0, 'INVALID_ARGUMENT', 'master.scriptText is required')
  assertDomain(LOCALE.test(input.locale), 'INVALID_ARGUMENT', 'master.locale is invalid')

  const artifacts = assertArtifacts(input.artifacts)
  const audioDurationMs = positiveDuration(input.audioDurationMs, 'master.audioDurationMs')
  const videoDurationMs = positiveDuration(input.videoDurationMs, 'master.videoDurationMs')
  const durationMs = positiveDuration(input.durationMs, 'master.durationMs')
  assertDomain(
    durationMs === audioDurationMs,
    'INVALID_ARGUMENT',
    'master.durationMs must equal the audio duration because audio governs the timeline',
  )
  assertDomain(
    Math.abs(videoDurationMs - audioDurationMs) <= SYNTHETIC_MASTER_DURATION_TOLERANCE_MS,
    'INVALID_ARGUMENT',
    'master video and audio durations disagree beyond one frame',
  )

  for (const [field, value] of Object.entries({
    adapterId: input.provenance.adapterId,
    adapterVersion: input.provenance.adapterVersion,
    capability: input.provenance.capability,
    providerJobId: input.provenance.providerJobId,
  })) {
    assertDomain(ID.test(value), 'INVALID_ARGUMENT', `master.provenance.${field} is invalid`)
  }
  assertDomain(
    input.provenance.modelRef === null || ID.test(input.provenance.modelRef),
    'INVALID_ARGUMENT',
    'master.provenance.modelRef is invalid',
  )
  assertDomain(HASH.test(input.provenance.adapterConfigHash), 'INVALID_ARGUMENT', 'master.provenance.adapterConfigHash is invalid')
  assertDomain(
    input.provenance.providerJobRef.trim().length > 0 && input.provenance.providerJobRef.length <= 256,
    'INVALID_ARGUMENT',
    'master.provenance.providerJobRef is required',
  )

  assertDomain(CURRENCY.test(input.cost.currency), 'INVALID_ARGUMENT', 'master.cost.currency is invalid')
  assertDomain(
    Number.isSafeInteger(input.cost.minorUnits) && input.cost.minorUnits >= 0,
    'INVALID_ARGUMENT',
    'master.cost.minorUnits is invalid',
  )
  assertDomain(
    Number.isSafeInteger(input.cost.latencyMs) && input.cost.latencyMs >= 0,
    'INVALID_ARGUMENT',
    'master.cost.latencyMs is invalid',
  )

  assertDomain(ID.test(input.critic.reportId), 'INVALID_ARGUMENT', 'master.critic.reportId is invalid')
  assertDomain(HASH.test(input.critic.reportHash), 'INVALID_ARGUMENT', 'master.critic.reportHash is invalid')
  assertDomain(
    input.critic.decision === 'approved',
    'INVALID_ARGUMENT',
    'a master can only be sealed by an approved critic report',
  )

  assertDomain(input.lineage.length > 0, 'INVALID_ARGUMENT', 'master.lineage is required')
  const lineage: string[] = []
  for (const entry of input.lineage) {
    assertDomain(ID.test(entry), 'INVALID_ARGUMENT', 'master.lineage entry is invalid')
    assertDomain(!lineage.includes(entry), 'INVALID_ARGUMENT', 'master.lineage entry is duplicated')
    lineage.push(entry)
  }

  const scriptHash = createHash('sha256').update(scriptText, 'utf8').digest('hex')
  assertDomain(
    input.scriptHash === undefined || input.scriptHash === scriptHash,
    'INVALID_ARGUMENT',
    'master.scriptHash does not match master.scriptText',
  )

  const master: Omit<SyntheticMasterAsset, 'masterHash'> = {
    schemaVersion: SYNTHETIC_MASTER_ASSET_SCHEMA_VERSION,
    id: input.id,
    workspaceId: input.workspaceId,
    projectId: input.projectId,
    projectVersionId: input.projectVersionId,
    profileId: input.profileId,
    profileSnapshotId: input.profileSnapshotId,
    profileVersion: input.profileVersion,
    consentSnapshotHash: input.consentSnapshotHash,
    authorizationHash: input.authorizationHash,
    rightsSnapshotId: input.rightsSnapshotId,
    artifacts,
    scriptText,
    scriptHash,
    alignmentHash: input.alignmentHash,
    locale: input.locale,
    durationMs,
    audioDurationMs,
    videoDurationMs,
    provenance: Object.freeze({ ...input.provenance }),
    cost: Object.freeze({ ...input.cost }),
    critic: Object.freeze({ ...input.critic }),
    lineage: Object.freeze(lineage),
    createdAt: instant(input.createdAt, 'master.createdAt'),
  }
  return Object.freeze({ ...master, masterHash: calculateSyntheticMasterHash(master) })
}

/**
 * Fail-closed rehydration. A row whose stored hash disagrees with its content
 * was tampered with or written by an older writer; either way it must never be
 * served as an authoritative master.
 */
export function assertSyntheticMasterIntegrity(master: Readonly<SyntheticMasterAsset>): Readonly<SyntheticMasterAsset> {
  const recomputed = calculateSyntheticMasterHash(master)
  assertDomain(
    recomputed === master.masterHash,
    'PERSISTENCE_CONFLICT',
    'synthetic master hash does not match its stored content',
  )
  return master
}

export function findSyntheticMasterArtifact(
  master: Readonly<SyntheticMasterAsset>,
  role: SyntheticMasterArtifactRole,
): Readonly<SyntheticMasterArtifactRef> {
  const artifact = master.artifacts.find((entry) => entry.role === role)
  assertDomain(Boolean(artifact), 'NOT_FOUND', `master has no ${role} artifact`)
  return artifact!
}
