import { createHash } from 'node:crypto'

import { calculateCanonicalHash } from './canonical-hash.ts'
import { assertDomain } from './errors.ts'
import { SYNTHETIC_SCRIPT_SEGMENTATION_VERSION } from './synthetic-script-segmentation.ts'

/**
 * One canonical identity for every kind of synthetic work, superseding the
 * audio-only `synthetic-block-cache-key/v1`.
 *
 * The rule is the same for all operations: the key carries only what changes
 * the generated bytes or their preparation. Project, block position, editorial
 * timestamps, cost, timeout, retry count, consent and the moment of the lookup
 * are deliberately absent — eligibility is re-validated on every hit instead of
 * being baked into the identity, so renewing a consent never fabricates a paid
 * regeneration and revoking one never leaves a reusable address behind.
 */
export const SYNTHETIC_CACHE_IDENTITY_VERSION = 'synthetic-cache-identity/v1' as const

/** Retained so v1 audio keys stay readable and comparable across the wave. */
export const SYNTHETIC_BLOCK_CACHE_KEY_VERSION = 'synthetic-block-cache-key/v1' as const

const ID = /^[A-Za-z0-9][A-Za-z0-9._:/-]{2,127}$/
const HASH = /^[a-f0-9]{64}$/
const LOCALE = /^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$/

export const SYNTHETIC_CACHE_OPERATIONS = Object.freeze(['tts', 'audio-avatar'] as const)
export type SyntheticCacheOperation = (typeof SYNTHETIC_CACHE_OPERATIONS)[number]

/**
 * The voice-side identity that changes a TTS result. Presenter visual
 * attributes are deliberately absent: audio depends on the voice, not on
 * wardrobe or framing, so a profile version that keeps the same voice keeps
 * every audio cache hit.
 */
export interface SyntheticVoiceIdentity {
  adapterId: string
  adapterVersion: string
  voiceId: string
  voiceVersion: number
  modelRef: string | null
  outputFormat: 'mp3' | 'wav'
  /**
   * Canonical hash of only the synthesis-relevant adapter configuration.
   * Observational config (cost, timeouts, byte limits) must never reach this
   * hash: it does not change the audio and would fabricate cache misses.
   */
  synthesisConfigHash: string
}

/**
 * The avatar-side identity that changes rendered video. The driving audio
 * enters by checksum, because the same script re-synthesised produces
 * different bytes and therefore a different performance.
 */
export interface SyntheticAvatarIdentity {
  adapterId: string
  adapterVersion: string
  avatarIdentityRef: string
  presenterVersion: number
  modelRef: string | null
  outputFormat: string
  /** Content address of the audio that drives the avatar. */
  audioChecksum: string
  /** Only render-relevant adapter configuration. */
  renderConfigHash: string
  /** Direction and background change the pixels, so they belong to identity. */
  direction: string | null
  background: string | null
}

export interface SyntheticTtsCacheSubject {
  operation: 'tts'
  exactText: string
  locale: string
  voice: Readonly<SyntheticVoiceIdentity>
  pronunciationDictionaryRef?: string | null
}

export interface SyntheticAvatarCacheSubject {
  operation: 'audio-avatar'
  locale: string
  avatar: Readonly<SyntheticAvatarIdentity>
}

export type SyntheticCacheSubject = SyntheticTtsCacheSubject | SyntheticAvatarCacheSubject

export function createSyntheticVoiceIdentity(input: Omit<SyntheticVoiceIdentity, 'synthesisConfigHash'> & {
  synthesisConfig: Readonly<Record<string, unknown>>
}): Readonly<SyntheticVoiceIdentity> {
  assertDomain(ID.test(input.adapterId) && ID.test(input.adapterVersion), 'INVALID_ARGUMENT', 'Voice adapter identity is invalid')
  assertDomain(ID.test(input.voiceId), 'INVALID_ARGUMENT', 'Voice id is invalid')
  assertDomain(Number.isSafeInteger(input.voiceVersion) && input.voiceVersion >= 1, 'INVALID_ARGUMENT', 'Voice version is invalid')
  assertDomain(input.modelRef === null || ID.test(input.modelRef), 'INVALID_ARGUMENT', 'Voice model reference is invalid')
  assertDomain(['mp3', 'wav'].includes(input.outputFormat), 'INVALID_ARGUMENT', 'Voice output format is invalid')
  return Object.freeze({
    adapterId: input.adapterId,
    adapterVersion: input.adapterVersion,
    voiceId: input.voiceId,
    voiceVersion: input.voiceVersion,
    modelRef: input.modelRef,
    outputFormat: input.outputFormat,
    synthesisConfigHash: calculateCanonicalHash({
      schemaVersion: 'synthetic-block-synthesis-config/v1',
      config: input.synthesisConfig,
    }),
  })
}

export function createSyntheticAvatarIdentity(input: Omit<SyntheticAvatarIdentity, 'renderConfigHash'> & {
  renderConfig: Readonly<Record<string, unknown>>
}): Readonly<SyntheticAvatarIdentity> {
  assertDomain(ID.test(input.adapterId) && ID.test(input.adapterVersion), 'INVALID_ARGUMENT', 'Avatar adapter identity is invalid')
  assertDomain(ID.test(input.avatarIdentityRef), 'INVALID_ARGUMENT', 'Avatar identity reference is invalid')
  assertDomain(
    Number.isSafeInteger(input.presenterVersion) && input.presenterVersion >= 1,
    'INVALID_ARGUMENT',
    'Avatar presenter version is invalid',
  )
  assertDomain(input.modelRef === null || ID.test(input.modelRef), 'INVALID_ARGUMENT', 'Avatar model reference is invalid')
  assertDomain(input.outputFormat.trim().length > 0, 'INVALID_ARGUMENT', 'Avatar output format is required')
  assertDomain(HASH.test(input.audioChecksum), 'INVALID_ARGUMENT', 'Avatar driving audio checksum is invalid')
  return Object.freeze({
    adapterId: input.adapterId,
    adapterVersion: input.adapterVersion,
    avatarIdentityRef: input.avatarIdentityRef,
    presenterVersion: input.presenterVersion,
    modelRef: input.modelRef,
    outputFormat: input.outputFormat,
    audioChecksum: input.audioChecksum,
    renderConfigHash: calculateCanonicalHash({
      schemaVersion: 'synthetic-avatar-render-config/v1',
      config: input.renderConfig,
    }),
    direction: input.direction,
    background: input.background,
  })
}

/**
 * Canonical body of a cache identity: the exact object that is hashed. It is
 * exported so tests and evidence can show what participates without
 * re-deriving the rule from the hash.
 */
export function syntheticCacheIdentityBody(subject: Readonly<SyntheticCacheSubject>): Readonly<Record<string, unknown>> {
  assertDomain(LOCALE.test(subject.locale), 'INVALID_ARGUMENT', 'Cache identity locale is invalid')
  if (subject.operation === 'tts') {
    assertDomain(subject.exactText.trim().length > 0, 'INVALID_ARGUMENT', 'Cache identity text is empty')
    assertDomain(HASH.test(subject.voice.synthesisConfigHash), 'INVALID_ARGUMENT', 'Cache identity synthesis config hash is invalid')
    return Object.freeze({
      schemaVersion: SYNTHETIC_BLOCK_CACHE_KEY_VERSION,
      segmentationVersion: SYNTHETIC_SCRIPT_SEGMENTATION_VERSION,
      scriptHash: createHash('sha256').update(subject.exactText, 'utf8').digest('hex'),
      locale: subject.locale,
      voice: {
        adapterId: subject.voice.adapterId,
        adapterVersion: subject.voice.adapterVersion,
        voiceId: subject.voice.voiceId,
        voiceVersion: subject.voice.voiceVersion,
        modelRef: subject.voice.modelRef,
        outputFormat: subject.voice.outputFormat,
        synthesisConfigHash: subject.voice.synthesisConfigHash,
      },
      pronunciationDictionaryRef: subject.pronunciationDictionaryRef ?? null,
    })
  }
  assertDomain(HASH.test(subject.avatar.renderConfigHash), 'INVALID_ARGUMENT', 'Cache identity render config hash is invalid')
  return Object.freeze({
    schemaVersion: 'synthetic-avatar-cache-key/v1',
    locale: subject.locale,
    avatar: {
      adapterId: subject.avatar.adapterId,
      adapterVersion: subject.avatar.adapterVersion,
      avatarIdentityRef: subject.avatar.avatarIdentityRef,
      presenterVersion: subject.avatar.presenterVersion,
      modelRef: subject.avatar.modelRef,
      outputFormat: subject.avatar.outputFormat,
      audioChecksum: subject.avatar.audioChecksum,
      renderConfigHash: subject.avatar.renderConfigHash,
      direction: subject.avatar.direction,
      background: subject.avatar.background,
    },
  })
}

/**
 * The cache address of a piece of synthetic work.
 *
 * TTS keys keep producing exactly the `synthetic-block-cache-key/v1` digest
 * they produced before this centralization, so every generation already
 * persisted stays reachable; avatar work gets its own versioned shape.
 */
export function calculateSyntheticCacheKey(subject: Readonly<SyntheticCacheSubject>): string {
  return calculateCanonicalHash(syntheticCacheIdentityBody(subject))
}

/**
 * Backwards-compatible entry point for audio blocks.
 */
export function calculateSyntheticBlockCacheKey(input: {
  exactText: string
  locale: string
  voice: Readonly<SyntheticVoiceIdentity>
  pronunciationDictionaryRef?: string | null
}): string {
  return calculateSyntheticCacheKey({
    operation: 'tts',
    exactText: input.exactText,
    locale: input.locale,
    voice: input.voice,
    ...(input.pronunciationDictionaryRef === undefined
      ? {}
      : { pronunciationDictionaryRef: input.pronunciationDictionaryRef }),
  })
}

/**
 * Fields that must never enter a cache identity. A drift sentinel asserts the
 * canonical body never grows one of them, so an accidental "just add the
 * project id" can be caught by a test instead of by a duplicated bill.
 */
export const SYNTHETIC_CACHE_IDENTITY_FORBIDDEN_FIELDS = Object.freeze([
  'projectId',
  'projectVersionId',
  'blockId',
  'position',
  'sequence',
  'occurrence',
  'planId',
  'consent',
  'consentSnapshotHash',
  'cost',
  'costMinorUnits',
  'currency',
  'timeoutMs',
  'retryCount',
  'attempt',
  'deadlineAt',
  'requestedAt',
  'createdAt',
  'updatedAt',
  'workspaceId',
  'actorId',
  'idempotencyKey',
] as const)

function collectKeys(value: unknown, into: Set<string>): void {
  if (Array.isArray(value)) {
    for (const entry of value) collectKeys(entry, into)
    return
  }
  if (value && typeof value === 'object') {
    for (const [key, nested] of Object.entries(value)) {
      into.add(key)
      collectKeys(nested, into)
    }
  }
}

export function assertSyntheticCacheIdentityShape(subject: Readonly<SyntheticCacheSubject>): void {
  const keys = new Set<string>()
  collectKeys(syntheticCacheIdentityBody(subject), keys)
  for (const forbidden of SYNTHETIC_CACHE_IDENTITY_FORBIDDEN_FIELDS) {
    assertDomain(
      !keys.has(forbidden),
      'INVALID_ARGUMENT',
      `Cache identity must not carry ${forbidden}: it does not change the generated bytes`,
    )
  }
}
